// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_Common/Qot_Common.proto

/*
Package Qot_Common is a generated protocol buffer package.

It is generated from these files:
	Qot_Common/Qot_Common.proto

It has these top-level messages:
	Security
	KLine
	OptionBasicQotExData
	BasicQot
	TimeShare
	SecurityStaticBasic
	WarrantStaticExData
	OptionStaticExData
	SecurityStaticInfo
	Broker
	Ticker
	OrderBook
	OrderDetail
	ShareHoldingChange
	SubInfo
	ConnSubInfo
	PlateInfo
*/
package Qot_Common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "futugg/pb/Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QotMarket int32

const (
	QotMarket_QotMarket_Unknown       QotMarket = 0
	QotMarket_QotMarket_HK_Security   QotMarket = 1
	QotMarket_QotMarket_HK_Future     QotMarket = 2
	QotMarket_QotMarket_US_Security   QotMarket = 11
	QotMarket_QotMarket_CNSH_Security QotMarket = 21
	QotMarket_QotMarket_CNSZ_Security QotMarket = 22
)

var QotMarket_name = map[int32]string{
	0:  "QotMarket_Unknown",
	1:  "QotMarket_HK_Security",
	2:  "QotMarket_HK_Future",
	11: "QotMarket_US_Security",
	21: "QotMarket_CNSH_Security",
	22: "QotMarket_CNSZ_Security",
}
var QotMarket_value = map[string]int32{
	"QotMarket_Unknown":       0,
	"QotMarket_HK_Security":   1,
	"QotMarket_HK_Future":     2,
	"QotMarket_US_Security":   11,
	"QotMarket_CNSH_Security": 21,
	"QotMarket_CNSZ_Security": 22,
}

func (x QotMarket) Enum() *QotMarket {
	p := new(QotMarket)
	*p = x
	return p
}
func (x QotMarket) String() string {
	return proto.EnumName(QotMarket_name, int32(x))
}
func (x *QotMarket) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QotMarket_value, data, "QotMarket")
	if err != nil {
		return err
	}
	*x = QotMarket(value)
	return nil
}
func (QotMarket) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SecurityType int32

const (
	SecurityType_SecurityType_Unknown  SecurityType = 0
	SecurityType_SecurityType_Bond     SecurityType = 1
	SecurityType_SecurityType_Bwrt     SecurityType = 2
	SecurityType_SecurityType_Eqty     SecurityType = 3
	SecurityType_SecurityType_Trust    SecurityType = 4
	SecurityType_SecurityType_Warrant  SecurityType = 5
	SecurityType_SecurityType_Index    SecurityType = 6
	SecurityType_SecurityType_Plate    SecurityType = 7
	SecurityType_SecurityType_Drvt     SecurityType = 8
	SecurityType_SecurityType_PlateSet SecurityType = 9
)

var SecurityType_name = map[int32]string{
	0: "SecurityType_Unknown",
	1: "SecurityType_Bond",
	2: "SecurityType_Bwrt",
	3: "SecurityType_Eqty",
	4: "SecurityType_Trust",
	5: "SecurityType_Warrant",
	6: "SecurityType_Index",
	7: "SecurityType_Plate",
	8: "SecurityType_Drvt",
	9: "SecurityType_PlateSet",
}
var SecurityType_value = map[string]int32{
	"SecurityType_Unknown":  0,
	"SecurityType_Bond":     1,
	"SecurityType_Bwrt":     2,
	"SecurityType_Eqty":     3,
	"SecurityType_Trust":    4,
	"SecurityType_Warrant":  5,
	"SecurityType_Index":    6,
	"SecurityType_Plate":    7,
	"SecurityType_Drvt":     8,
	"SecurityType_PlateSet": 9,
}

func (x SecurityType) Enum() *SecurityType {
	p := new(SecurityType)
	*p = x
	return p
}
func (x SecurityType) String() string {
	return proto.EnumName(SecurityType_name, int32(x))
}
func (x *SecurityType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SecurityType_value, data, "SecurityType")
	if err != nil {
		return err
	}
	*x = SecurityType(value)
	return nil
}
func (SecurityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PlateSetType int32

const (
	PlateSetType_PlateSetType_All      PlateSetType = 0
	PlateSetType_PlateSetType_Industry PlateSetType = 1
	PlateSetType_PlateSetType_Region   PlateSetType = 2
	PlateSetType_PlateSetType_Concept  PlateSetType = 3
	PlateSetType_PlateSetType_Other    PlateSetType = 4
)

var PlateSetType_name = map[int32]string{
	0: "PlateSetType_All",
	1: "PlateSetType_Industry",
	2: "PlateSetType_Region",
	3: "PlateSetType_Concept",
	4: "PlateSetType_Other",
}
var PlateSetType_value = map[string]int32{
	"PlateSetType_All":      0,
	"PlateSetType_Industry": 1,
	"PlateSetType_Region":   2,
	"PlateSetType_Concept":  3,
	"PlateSetType_Other":    4,
}

func (x PlateSetType) Enum() *PlateSetType {
	p := new(PlateSetType)
	*p = x
	return p
}
func (x PlateSetType) String() string {
	return proto.EnumName(PlateSetType_name, int32(x))
}
func (x *PlateSetType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlateSetType_value, data, "PlateSetType")
	if err != nil {
		return err
	}
	*x = PlateSetType(value)
	return nil
}
func (PlateSetType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WarrantType int32

const (
	WarrantType_WarrantType_Unknown WarrantType = 0
	WarrantType_WarrantType_Buy     WarrantType = 1
	WarrantType_WarrantType_Sell    WarrantType = 2
	WarrantType_WarrantType_Bull    WarrantType = 3
	WarrantType_WarrantType_Bear    WarrantType = 4
)

var WarrantType_name = map[int32]string{
	0: "WarrantType_Unknown",
	1: "WarrantType_Buy",
	2: "WarrantType_Sell",
	3: "WarrantType_Bull",
	4: "WarrantType_Bear",
}
var WarrantType_value = map[string]int32{
	"WarrantType_Unknown": 0,
	"WarrantType_Buy":     1,
	"WarrantType_Sell":    2,
	"WarrantType_Bull":    3,
	"WarrantType_Bear":    4,
}

func (x WarrantType) Enum() *WarrantType {
	p := new(WarrantType)
	*p = x
	return p
}
func (x WarrantType) String() string {
	return proto.EnumName(WarrantType_name, int32(x))
}
func (x *WarrantType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WarrantType_value, data, "WarrantType")
	if err != nil {
		return err
	}
	*x = WarrantType(value)
	return nil
}
func (WarrantType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type OptionType int32

const (
	OptionType_OptionType_Unknown OptionType = 0
	OptionType_OptionType_Call    OptionType = 1
	OptionType_OptionType_Put     OptionType = 2
)

var OptionType_name = map[int32]string{
	0: "OptionType_Unknown",
	1: "OptionType_Call",
	2: "OptionType_Put",
}
var OptionType_value = map[string]int32{
	"OptionType_Unknown": 0,
	"OptionType_Call":    1,
	"OptionType_Put":     2,
}

func (x OptionType) Enum() *OptionType {
	p := new(OptionType)
	*p = x
	return p
}
func (x OptionType) String() string {
	return proto.EnumName(OptionType_name, int32(x))
}
func (x *OptionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OptionType_value, data, "OptionType")
	if err != nil {
		return err
	}
	*x = OptionType(value)
	return nil
}
func (OptionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type QotMarketState int32

const (
	QotMarketState_QotMarketState_None                 QotMarketState = 0
	QotMarketState_QotMarketState_Auction              QotMarketState = 1
	QotMarketState_QotMarketState_WaitingOpen          QotMarketState = 2
	QotMarketState_QotMarketState_Morning              QotMarketState = 3
	QotMarketState_QotMarketState_Rest                 QotMarketState = 4
	QotMarketState_QotMarketState_Afternoon            QotMarketState = 5
	QotMarketState_QotMarketState_Closed               QotMarketState = 6
	QotMarketState_QotMarketState_PreMarketBegin       QotMarketState = 8
	QotMarketState_QotMarketState_PreMarketEnd         QotMarketState = 9
	QotMarketState_QotMarketState_AfterHoursBegin      QotMarketState = 10
	QotMarketState_QotMarketState_AfterHoursEnd        QotMarketState = 11
	QotMarketState_QotMarketState_NightOpen            QotMarketState = 13
	QotMarketState_QotMarketState_NightEnd             QotMarketState = 14
	QotMarketState_QotMarketState_FutureDayOpen        QotMarketState = 15
	QotMarketState_QotMarketState_FutureDayBreak       QotMarketState = 16
	QotMarketState_QotMarketState_FutureDayClose       QotMarketState = 17
	QotMarketState_QotMarketState_FutureDayWaitForOpen QotMarketState = 18
	QotMarketState_QotMarketState_HkCas                QotMarketState = 19
)

var QotMarketState_name = map[int32]string{
	0:  "QotMarketState_None",
	1:  "QotMarketState_Auction",
	2:  "QotMarketState_WaitingOpen",
	3:  "QotMarketState_Morning",
	4:  "QotMarketState_Rest",
	5:  "QotMarketState_Afternoon",
	6:  "QotMarketState_Closed",
	8:  "QotMarketState_PreMarketBegin",
	9:  "QotMarketState_PreMarketEnd",
	10: "QotMarketState_AfterHoursBegin",
	11: "QotMarketState_AfterHoursEnd",
	13: "QotMarketState_NightOpen",
	14: "QotMarketState_NightEnd",
	15: "QotMarketState_FutureDayOpen",
	16: "QotMarketState_FutureDayBreak",
	17: "QotMarketState_FutureDayClose",
	18: "QotMarketState_FutureDayWaitForOpen",
	19: "QotMarketState_HkCas",
}
var QotMarketState_value = map[string]int32{
	"QotMarketState_None":                 0,
	"QotMarketState_Auction":              1,
	"QotMarketState_WaitingOpen":          2,
	"QotMarketState_Morning":              3,
	"QotMarketState_Rest":                 4,
	"QotMarketState_Afternoon":            5,
	"QotMarketState_Closed":               6,
	"QotMarketState_PreMarketBegin":       8,
	"QotMarketState_PreMarketEnd":         9,
	"QotMarketState_AfterHoursBegin":      10,
	"QotMarketState_AfterHoursEnd":        11,
	"QotMarketState_NightOpen":            13,
	"QotMarketState_NightEnd":             14,
	"QotMarketState_FutureDayOpen":        15,
	"QotMarketState_FutureDayBreak":       16,
	"QotMarketState_FutureDayClose":       17,
	"QotMarketState_FutureDayWaitForOpen": 18,
	"QotMarketState_HkCas":                19,
}

func (x QotMarketState) Enum() *QotMarketState {
	p := new(QotMarketState)
	*p = x
	return p
}
func (x QotMarketState) String() string {
	return proto.EnumName(QotMarketState_name, int32(x))
}
func (x *QotMarketState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QotMarketState_value, data, "QotMarketState")
	if err != nil {
		return err
	}
	*x = QotMarketState(value)
	return nil
}
func (QotMarketState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RehabType int32

const (
	RehabType_RehabType_None     RehabType = 0
	RehabType_RehabType_Forward  RehabType = 1
	RehabType_RehabType_Backward RehabType = 2
)

var RehabType_name = map[int32]string{
	0: "RehabType_None",
	1: "RehabType_Forward",
	2: "RehabType_Backward",
}
var RehabType_value = map[string]int32{
	"RehabType_None":     0,
	"RehabType_Forward":  1,
	"RehabType_Backward": 2,
}

func (x RehabType) Enum() *RehabType {
	p := new(RehabType)
	*p = x
	return p
}
func (x RehabType) String() string {
	return proto.EnumName(RehabType_name, int32(x))
}
func (x *RehabType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RehabType_value, data, "RehabType")
	if err != nil {
		return err
	}
	*x = RehabType(value)
	return nil
}
func (RehabType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 枚举值兼容旧协议定义
// 新类型季K,年K,3分K暂时没有支持历史K线
type KLType int32

const (
	KLType_KLType_Unknown KLType = 0
	KLType_KLType_1Min    KLType = 1
	KLType_KLType_Day     KLType = 2
	KLType_KLType_Week    KLType = 3
	KLType_KLType_Month   KLType = 4
	KLType_KLType_Year    KLType = 5
	KLType_KLType_5Min    KLType = 6
	KLType_KLType_15Min   KLType = 7
	KLType_KLType_30Min   KLType = 8
	KLType_KLType_60Min   KLType = 9
	KLType_KLType_3Min    KLType = 10
	KLType_KLType_Quarter KLType = 11
)

var KLType_name = map[int32]string{
	0:  "KLType_Unknown",
	1:  "KLType_1Min",
	2:  "KLType_Day",
	3:  "KLType_Week",
	4:  "KLType_Month",
	5:  "KLType_Year",
	6:  "KLType_5Min",
	7:  "KLType_15Min",
	8:  "KLType_30Min",
	9:  "KLType_60Min",
	10: "KLType_3Min",
	11: "KLType_Quarter",
}
var KLType_value = map[string]int32{
	"KLType_Unknown": 0,
	"KLType_1Min":    1,
	"KLType_Day":     2,
	"KLType_Week":    3,
	"KLType_Month":   4,
	"KLType_Year":    5,
	"KLType_5Min":    6,
	"KLType_15Min":   7,
	"KLType_30Min":   8,
	"KLType_60Min":   9,
	"KLType_3Min":    10,
	"KLType_Quarter": 11,
}

func (x KLType) Enum() *KLType {
	p := new(KLType)
	*p = x
	return p
}
func (x KLType) String() string {
	return proto.EnumName(KLType_name, int32(x))
}
func (x *KLType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KLType_value, data, "KLType")
	if err != nil {
		return err
	}
	*x = KLType(value)
	return nil
}
func (KLType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type KLFields int32

const (
	KLFields_KLFields_None         KLFields = 0
	KLFields_KLFields_High         KLFields = 1
	KLFields_KLFields_Open         KLFields = 2
	KLFields_KLFields_Low          KLFields = 4
	KLFields_KLFields_Close        KLFields = 8
	KLFields_KLFields_LastClose    KLFields = 16
	KLFields_KLFields_Volume       KLFields = 32
	KLFields_KLFields_Turnover     KLFields = 64
	KLFields_KLFields_TurnoverRate KLFields = 128
	KLFields_KLFields_PE           KLFields = 256
	KLFields_KLFields_ChangeRate   KLFields = 512
)

var KLFields_name = map[int32]string{
	0:   "KLFields_None",
	1:   "KLFields_High",
	2:   "KLFields_Open",
	4:   "KLFields_Low",
	8:   "KLFields_Close",
	16:  "KLFields_LastClose",
	32:  "KLFields_Volume",
	64:  "KLFields_Turnover",
	128: "KLFields_TurnoverRate",
	256: "KLFields_PE",
	512: "KLFields_ChangeRate",
}
var KLFields_value = map[string]int32{
	"KLFields_None":         0,
	"KLFields_High":         1,
	"KLFields_Open":         2,
	"KLFields_Low":          4,
	"KLFields_Close":        8,
	"KLFields_LastClose":    16,
	"KLFields_Volume":       32,
	"KLFields_Turnover":     64,
	"KLFields_TurnoverRate": 128,
	"KLFields_PE":           256,
	"KLFields_ChangeRate":   512,
}

func (x KLFields) Enum() *KLFields {
	p := new(KLFields)
	*p = x
	return p
}
func (x KLFields) String() string {
	return proto.EnumName(KLFields_name, int32(x))
}
func (x *KLFields) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KLFields_value, data, "KLFields")
	if err != nil {
		return err
	}
	*x = KLFields(value)
	return nil
}
func (KLFields) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// 订阅类型
// 枚举值兼容旧协议定义
type SubType int32

const (
	SubType_SubType_None        SubType = 0
	SubType_SubType_Basic       SubType = 1
	SubType_SubType_OrderBook   SubType = 2
	SubType_SubType_Ticker      SubType = 4
	SubType_SubType_RT          SubType = 5
	SubType_SubType_KL_Day      SubType = 6
	SubType_SubType_KL_5Min     SubType = 7
	SubType_SubType_KL_15Min    SubType = 8
	SubType_SubType_KL_30Min    SubType = 9
	SubType_SubType_KL_60Min    SubType = 10
	SubType_SubType_KL_1Min     SubType = 11
	SubType_SubType_KL_Week     SubType = 12
	SubType_SubType_KL_Month    SubType = 13
	SubType_SubType_Broker      SubType = 14
	SubType_SubType_KL_Qurater  SubType = 15
	SubType_SubType_KL_Year     SubType = 16
	SubType_SubType_KL_3Min     SubType = 17
	SubType_SubType_OrderDetail SubType = 18
)

var SubType_name = map[int32]string{
	0:  "SubType_None",
	1:  "SubType_Basic",
	2:  "SubType_OrderBook",
	4:  "SubType_Ticker",
	5:  "SubType_RT",
	6:  "SubType_KL_Day",
	7:  "SubType_KL_5Min",
	8:  "SubType_KL_15Min",
	9:  "SubType_KL_30Min",
	10: "SubType_KL_60Min",
	11: "SubType_KL_1Min",
	12: "SubType_KL_Week",
	13: "SubType_KL_Month",
	14: "SubType_Broker",
	15: "SubType_KL_Qurater",
	16: "SubType_KL_Year",
	17: "SubType_KL_3Min",
	18: "SubType_OrderDetail",
}
var SubType_value = map[string]int32{
	"SubType_None":        0,
	"SubType_Basic":       1,
	"SubType_OrderBook":   2,
	"SubType_Ticker":      4,
	"SubType_RT":          5,
	"SubType_KL_Day":      6,
	"SubType_KL_5Min":     7,
	"SubType_KL_15Min":    8,
	"SubType_KL_30Min":    9,
	"SubType_KL_60Min":    10,
	"SubType_KL_1Min":     11,
	"SubType_KL_Week":     12,
	"SubType_KL_Month":    13,
	"SubType_Broker":      14,
	"SubType_KL_Qurater":  15,
	"SubType_KL_Year":     16,
	"SubType_KL_3Min":     17,
	"SubType_OrderDetail": 18,
}

func (x SubType) Enum() *SubType {
	p := new(SubType)
	*p = x
	return p
}
func (x SubType) String() string {
	return proto.EnumName(SubType_name, int32(x))
}
func (x *SubType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SubType_value, data, "SubType")
	if err != nil {
		return err
	}
	*x = SubType(value)
	return nil
}
func (SubType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type TickerDirection int32

const (
	TickerDirection_TickerDirection_Unknown TickerDirection = 0
	TickerDirection_TickerDirection_Bid     TickerDirection = 1
	TickerDirection_TickerDirection_Ask     TickerDirection = 2
	TickerDirection_TickerDirection_Neutral TickerDirection = 3
)

var TickerDirection_name = map[int32]string{
	0: "TickerDirection_Unknown",
	1: "TickerDirection_Bid",
	2: "TickerDirection_Ask",
	3: "TickerDirection_Neutral",
}
var TickerDirection_value = map[string]int32{
	"TickerDirection_Unknown": 0,
	"TickerDirection_Bid":     1,
	"TickerDirection_Ask":     2,
	"TickerDirection_Neutral": 3,
}

func (x TickerDirection) Enum() *TickerDirection {
	p := new(TickerDirection)
	*p = x
	return p
}
func (x TickerDirection) String() string {
	return proto.EnumName(TickerDirection_name, int32(x))
}
func (x *TickerDirection) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TickerDirection_value, data, "TickerDirection")
	if err != nil {
		return err
	}
	*x = TickerDirection(value)
	return nil
}
func (TickerDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type TickerType int32

const (
	TickerType_TickerType_Unknown                 TickerType = 0
	TickerType_TickerType_Automatch               TickerType = 1
	TickerType_TickerType_Late                    TickerType = 2
	TickerType_TickerType_NoneAutomatch           TickerType = 3
	TickerType_TickerType_InterAutomatch          TickerType = 4
	TickerType_TickerType_InterNoneAutomatch      TickerType = 5
	TickerType_TickerType_OddLot                  TickerType = 6
	TickerType_TickerType_Auction                 TickerType = 7
	TickerType_TickerType_Bulk                    TickerType = 8
	TickerType_TickerType_Crash                   TickerType = 9
	TickerType_TickerType_CrossMarket             TickerType = 10
	TickerType_TickerType_BulkSold                TickerType = 11
	TickerType_TickerType_FreeOnBoard             TickerType = 12
	TickerType_TickerType_Rule127Or155            TickerType = 13
	TickerType_TickerType_Delay                   TickerType = 14
	TickerType_TickerType_MarketCenterClosePrice  TickerType = 15
	TickerType_TickerType_NextDay                 TickerType = 16
	TickerType_TickerType_MarketCenterOpening     TickerType = 17
	TickerType_TickerType_PriorReferencePrice     TickerType = 18
	TickerType_TickerType_MarketCenterOpenPrice   TickerType = 19
	TickerType_TickerType_Seller                  TickerType = 20
	TickerType_TickerType_T                       TickerType = 21
	TickerType_TickerType_ExtendedTradingHours    TickerType = 22
	TickerType_TickerType_Contingent              TickerType = 23
	TickerType_TickerType_AveragePrice            TickerType = 24
	TickerType_TickerType_OTCSold                 TickerType = 25
	TickerType_TickerType_OddLotCrossMarket       TickerType = 26
	TickerType_TickerType_DerivativelyPriced      TickerType = 27
	TickerType_TickerType_ReOpeningPriced         TickerType = 28
	TickerType_TickerType_ClosingPriced           TickerType = 29
	TickerType_TickerType_ComprehensiveDelayPrice TickerType = 30
)

var TickerType_name = map[int32]string{
	0:  "TickerType_Unknown",
	1:  "TickerType_Automatch",
	2:  "TickerType_Late",
	3:  "TickerType_NoneAutomatch",
	4:  "TickerType_InterAutomatch",
	5:  "TickerType_InterNoneAutomatch",
	6:  "TickerType_OddLot",
	7:  "TickerType_Auction",
	8:  "TickerType_Bulk",
	9:  "TickerType_Crash",
	10: "TickerType_CrossMarket",
	11: "TickerType_BulkSold",
	12: "TickerType_FreeOnBoard",
	13: "TickerType_Rule127Or155",
	14: "TickerType_Delay",
	15: "TickerType_MarketCenterClosePrice",
	16: "TickerType_NextDay",
	17: "TickerType_MarketCenterOpening",
	18: "TickerType_PriorReferencePrice",
	19: "TickerType_MarketCenterOpenPrice",
	20: "TickerType_Seller",
	21: "TickerType_T",
	22: "TickerType_ExtendedTradingHours",
	23: "TickerType_Contingent",
	24: "TickerType_AveragePrice",
	25: "TickerType_OTCSold",
	26: "TickerType_OddLotCrossMarket",
	27: "TickerType_DerivativelyPriced",
	28: "TickerType_ReOpeningPriced",
	29: "TickerType_ClosingPriced",
	30: "TickerType_ComprehensiveDelayPrice",
}
var TickerType_value = map[string]int32{
	"TickerType_Unknown":                 0,
	"TickerType_Automatch":               1,
	"TickerType_Late":                    2,
	"TickerType_NoneAutomatch":           3,
	"TickerType_InterAutomatch":          4,
	"TickerType_InterNoneAutomatch":      5,
	"TickerType_OddLot":                  6,
	"TickerType_Auction":                 7,
	"TickerType_Bulk":                    8,
	"TickerType_Crash":                   9,
	"TickerType_CrossMarket":             10,
	"TickerType_BulkSold":                11,
	"TickerType_FreeOnBoard":             12,
	"TickerType_Rule127Or155":            13,
	"TickerType_Delay":                   14,
	"TickerType_MarketCenterClosePrice":  15,
	"TickerType_NextDay":                 16,
	"TickerType_MarketCenterOpening":     17,
	"TickerType_PriorReferencePrice":     18,
	"TickerType_MarketCenterOpenPrice":   19,
	"TickerType_Seller":                  20,
	"TickerType_T":                       21,
	"TickerType_ExtendedTradingHours":    22,
	"TickerType_Contingent":              23,
	"TickerType_AveragePrice":            24,
	"TickerType_OTCSold":                 25,
	"TickerType_OddLotCrossMarket":       26,
	"TickerType_DerivativelyPriced":      27,
	"TickerType_ReOpeningPriced":         28,
	"TickerType_ClosingPriced":           29,
	"TickerType_ComprehensiveDelayPrice": 30,
}

func (x TickerType) Enum() *TickerType {
	p := new(TickerType)
	*p = x
	return p
}
func (x TickerType) String() string {
	return proto.EnumName(TickerType_name, int32(x))
}
func (x *TickerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TickerType_value, data, "TickerType")
	if err != nil {
		return err
	}
	*x = TickerType(value)
	return nil
}
func (TickerType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type DarkStatus int32

const (
	DarkStatus_DarkStatus_None    DarkStatus = 0
	DarkStatus_DarkStatus_Trading DarkStatus = 1
	DarkStatus_DarkStatus_End     DarkStatus = 2
)

var DarkStatus_name = map[int32]string{
	0: "DarkStatus_None",
	1: "DarkStatus_Trading",
	2: "DarkStatus_End",
}
var DarkStatus_value = map[string]int32{
	"DarkStatus_None":    0,
	"DarkStatus_Trading": 1,
	"DarkStatus_End":     2,
}

func (x DarkStatus) Enum() *DarkStatus {
	p := new(DarkStatus)
	*p = x
	return p
}
func (x DarkStatus) String() string {
	return proto.EnumName(DarkStatus_name, int32(x))
}
func (x *DarkStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DarkStatus_value, data, "DarkStatus")
	if err != nil {
		return err
	}
	*x = DarkStatus(value)
	return nil
}
func (DarkStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type HolderCategory int32

const (
	HolderCategory_HolderCategory_Unknow        HolderCategory = 0
	HolderCategory_HolderCategory_Agency        HolderCategory = 1
	HolderCategory_HolderCategory_Fund          HolderCategory = 2
	HolderCategory_HolderCategory_SeniorManager HolderCategory = 3
)

var HolderCategory_name = map[int32]string{
	0: "HolderCategory_Unknow",
	1: "HolderCategory_Agency",
	2: "HolderCategory_Fund",
	3: "HolderCategory_SeniorManager",
}
var HolderCategory_value = map[string]int32{
	"HolderCategory_Unknow":        0,
	"HolderCategory_Agency":        1,
	"HolderCategory_Fund":          2,
	"HolderCategory_SeniorManager": 3,
}

func (x HolderCategory) Enum() *HolderCategory {
	p := new(HolderCategory)
	*p = x
	return p
}
func (x HolderCategory) String() string {
	return proto.EnumName(HolderCategory_name, int32(x))
}
func (x *HolderCategory) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HolderCategory_value, data, "HolderCategory")
	if err != nil {
		return err
	}
	*x = HolderCategory(value)
	return nil
}
func (HolderCategory) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// 推送数据的分类，目前只有逐笔在使用
type PushDataType int32

const (
	PushDataType_PushDataType_Unknow    PushDataType = 0
	PushDataType_PushDataType_Realtime  PushDataType = 1
	PushDataType_PushDataType_ByDisConn PushDataType = 2
	PushDataType_PushDataType_Cache     PushDataType = 3
)

var PushDataType_name = map[int32]string{
	0: "PushDataType_Unknow",
	1: "PushDataType_Realtime",
	2: "PushDataType_ByDisConn",
	3: "PushDataType_Cache",
}
var PushDataType_value = map[string]int32{
	"PushDataType_Unknow":    0,
	"PushDataType_Realtime":  1,
	"PushDataType_ByDisConn": 2,
	"PushDataType_Cache":     3,
}

func (x PushDataType) Enum() *PushDataType {
	p := new(PushDataType)
	*p = x
	return p
}
func (x PushDataType) String() string {
	return proto.EnumName(PushDataType_name, int32(x))
}
func (x *PushDataType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PushDataType_value, data, "PushDataType")
	if err != nil {
		return err
	}
	*x = PushDataType(value)
	return nil
}
func (PushDataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// 两个字段确定一支股票
type Security struct {
	Market           *int32  `protobuf:"varint,1,req,name=market" json:"market,omitempty"`
	Code             *string `protobuf:"bytes,2,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Security) Reset()                    { *m = Security{} }
func (m *Security) String() string            { return proto.CompactTextString(m) }
func (*Security) ProtoMessage()               {}
func (*Security) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Security) GetMarket() int32 {
	if m != nil && m.Market != nil {
		return *m.Market
	}
	return 0
}

func (m *Security) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type KLine struct {
	Time             *string  `protobuf:"bytes,1,req,name=time" json:"time,omitempty"`
	IsBlank          *bool    `protobuf:"varint,2,req,name=isBlank" json:"isBlank,omitempty"`
	HighPrice        *float64 `protobuf:"fixed64,3,opt,name=highPrice" json:"highPrice,omitempty"`
	OpenPrice        *float64 `protobuf:"fixed64,4,opt,name=openPrice" json:"openPrice,omitempty"`
	LowPrice         *float64 `protobuf:"fixed64,5,opt,name=lowPrice" json:"lowPrice,omitempty"`
	ClosePrice       *float64 `protobuf:"fixed64,6,opt,name=closePrice" json:"closePrice,omitempty"`
	LastClosePrice   *float64 `protobuf:"fixed64,7,opt,name=lastClosePrice" json:"lastClosePrice,omitempty"`
	Volume           *int64   `protobuf:"varint,8,opt,name=volume" json:"volume,omitempty"`
	Turnover         *float64 `protobuf:"fixed64,9,opt,name=turnover" json:"turnover,omitempty"`
	TurnoverRate     *float64 `protobuf:"fixed64,10,opt,name=turnoverRate" json:"turnoverRate,omitempty"`
	Pe               *float64 `protobuf:"fixed64,11,opt,name=pe" json:"pe,omitempty"`
	ChangeRate       *float64 `protobuf:"fixed64,12,opt,name=changeRate" json:"changeRate,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *KLine) Reset()                    { *m = KLine{} }
func (m *KLine) String() string            { return proto.CompactTextString(m) }
func (*KLine) ProtoMessage()               {}
func (*KLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KLine) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *KLine) GetIsBlank() bool {
	if m != nil && m.IsBlank != nil {
		return *m.IsBlank
	}
	return false
}

func (m *KLine) GetHighPrice() float64 {
	if m != nil && m.HighPrice != nil {
		return *m.HighPrice
	}
	return 0
}

func (m *KLine) GetOpenPrice() float64 {
	if m != nil && m.OpenPrice != nil {
		return *m.OpenPrice
	}
	return 0
}

func (m *KLine) GetLowPrice() float64 {
	if m != nil && m.LowPrice != nil {
		return *m.LowPrice
	}
	return 0
}

func (m *KLine) GetClosePrice() float64 {
	if m != nil && m.ClosePrice != nil {
		return *m.ClosePrice
	}
	return 0
}

func (m *KLine) GetLastClosePrice() float64 {
	if m != nil && m.LastClosePrice != nil {
		return *m.LastClosePrice
	}
	return 0
}

func (m *KLine) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *KLine) GetTurnover() float64 {
	if m != nil && m.Turnover != nil {
		return *m.Turnover
	}
	return 0
}

func (m *KLine) GetTurnoverRate() float64 {
	if m != nil && m.TurnoverRate != nil {
		return *m.TurnoverRate
	}
	return 0
}

func (m *KLine) GetPe() float64 {
	if m != nil && m.Pe != nil {
		return *m.Pe
	}
	return 0
}

func (m *KLine) GetChangeRate() float64 {
	if m != nil && m.ChangeRate != nil {
		return *m.ChangeRate
	}
	return 0
}

type OptionBasicQotExData struct {
	StrikePrice       *float64 `protobuf:"fixed64,1,req,name=strikePrice" json:"strikePrice,omitempty"`
	ContractSize      *int32   `protobuf:"varint,2,req,name=contractSize" json:"contractSize,omitempty"`
	OpenInterest      *int32   `protobuf:"varint,3,req,name=openInterest" json:"openInterest,omitempty"`
	ImpliedVolatility *float64 `protobuf:"fixed64,4,req,name=impliedVolatility" json:"impliedVolatility,omitempty"`
	Premium           *float64 `protobuf:"fixed64,5,req,name=premium" json:"premium,omitempty"`
	Delta             *float64 `protobuf:"fixed64,6,req,name=delta" json:"delta,omitempty"`
	Gamma             *float64 `protobuf:"fixed64,7,req,name=gamma" json:"gamma,omitempty"`
	Vega              *float64 `protobuf:"fixed64,8,req,name=vega" json:"vega,omitempty"`
	Theta             *float64 `protobuf:"fixed64,9,req,name=theta" json:"theta,omitempty"`
	Rho               *float64 `protobuf:"fixed64,10,req,name=rho" json:"rho,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *OptionBasicQotExData) Reset()                    { *m = OptionBasicQotExData{} }
func (m *OptionBasicQotExData) String() string            { return proto.CompactTextString(m) }
func (*OptionBasicQotExData) ProtoMessage()               {}
func (*OptionBasicQotExData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OptionBasicQotExData) GetStrikePrice() float64 {
	if m != nil && m.StrikePrice != nil {
		return *m.StrikePrice
	}
	return 0
}

func (m *OptionBasicQotExData) GetContractSize() int32 {
	if m != nil && m.ContractSize != nil {
		return *m.ContractSize
	}
	return 0
}

func (m *OptionBasicQotExData) GetOpenInterest() int32 {
	if m != nil && m.OpenInterest != nil {
		return *m.OpenInterest
	}
	return 0
}

func (m *OptionBasicQotExData) GetImpliedVolatility() float64 {
	if m != nil && m.ImpliedVolatility != nil {
		return *m.ImpliedVolatility
	}
	return 0
}

func (m *OptionBasicQotExData) GetPremium() float64 {
	if m != nil && m.Premium != nil {
		return *m.Premium
	}
	return 0
}

func (m *OptionBasicQotExData) GetDelta() float64 {
	if m != nil && m.Delta != nil {
		return *m.Delta
	}
	return 0
}

func (m *OptionBasicQotExData) GetGamma() float64 {
	if m != nil && m.Gamma != nil {
		return *m.Gamma
	}
	return 0
}

func (m *OptionBasicQotExData) GetVega() float64 {
	if m != nil && m.Vega != nil {
		return *m.Vega
	}
	return 0
}

func (m *OptionBasicQotExData) GetTheta() float64 {
	if m != nil && m.Theta != nil {
		return *m.Theta
	}
	return 0
}

func (m *OptionBasicQotExData) GetRho() float64 {
	if m != nil && m.Rho != nil {
		return *m.Rho
	}
	return 0
}

type BasicQot struct {
	Security         *Security             `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	IsSuspended      *bool                 `protobuf:"varint,2,req,name=isSuspended" json:"isSuspended,omitempty"`
	ListTime         *string               `protobuf:"bytes,3,req,name=listTime" json:"listTime,omitempty"`
	PriceSpread      *float64              `protobuf:"fixed64,4,req,name=priceSpread" json:"priceSpread,omitempty"`
	UpdateTime       *string               `protobuf:"bytes,5,req,name=updateTime" json:"updateTime,omitempty"`
	HighPrice        *float64              `protobuf:"fixed64,6,req,name=highPrice" json:"highPrice,omitempty"`
	OpenPrice        *float64              `protobuf:"fixed64,7,req,name=openPrice" json:"openPrice,omitempty"`
	LowPrice         *float64              `protobuf:"fixed64,8,req,name=lowPrice" json:"lowPrice,omitempty"`
	CurPrice         *float64              `protobuf:"fixed64,9,req,name=curPrice" json:"curPrice,omitempty"`
	LastClosePrice   *float64              `protobuf:"fixed64,10,req,name=lastClosePrice" json:"lastClosePrice,omitempty"`
	Volume           *int64                `protobuf:"varint,11,req,name=volume" json:"volume,omitempty"`
	Turnover         *float64              `protobuf:"fixed64,12,req,name=turnover" json:"turnover,omitempty"`
	TurnoverRate     *float64              `protobuf:"fixed64,13,req,name=turnoverRate" json:"turnoverRate,omitempty"`
	Amplitude        *float64              `protobuf:"fixed64,14,req,name=amplitude" json:"amplitude,omitempty"`
	DarkStatus       *int32                `protobuf:"varint,15,opt,name=darkStatus" json:"darkStatus,omitempty"`
	OptionExData     *OptionBasicQotExData `protobuf:"bytes,16,opt,name=optionExData" json:"optionExData,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *BasicQot) Reset()                    { *m = BasicQot{} }
func (m *BasicQot) String() string            { return proto.CompactTextString(m) }
func (*BasicQot) ProtoMessage()               {}
func (*BasicQot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BasicQot) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *BasicQot) GetIsSuspended() bool {
	if m != nil && m.IsSuspended != nil {
		return *m.IsSuspended
	}
	return false
}

func (m *BasicQot) GetListTime() string {
	if m != nil && m.ListTime != nil {
		return *m.ListTime
	}
	return ""
}

func (m *BasicQot) GetPriceSpread() float64 {
	if m != nil && m.PriceSpread != nil {
		return *m.PriceSpread
	}
	return 0
}

func (m *BasicQot) GetUpdateTime() string {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return ""
}

func (m *BasicQot) GetHighPrice() float64 {
	if m != nil && m.HighPrice != nil {
		return *m.HighPrice
	}
	return 0
}

func (m *BasicQot) GetOpenPrice() float64 {
	if m != nil && m.OpenPrice != nil {
		return *m.OpenPrice
	}
	return 0
}

func (m *BasicQot) GetLowPrice() float64 {
	if m != nil && m.LowPrice != nil {
		return *m.LowPrice
	}
	return 0
}

func (m *BasicQot) GetCurPrice() float64 {
	if m != nil && m.CurPrice != nil {
		return *m.CurPrice
	}
	return 0
}

func (m *BasicQot) GetLastClosePrice() float64 {
	if m != nil && m.LastClosePrice != nil {
		return *m.LastClosePrice
	}
	return 0
}

func (m *BasicQot) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *BasicQot) GetTurnover() float64 {
	if m != nil && m.Turnover != nil {
		return *m.Turnover
	}
	return 0
}

func (m *BasicQot) GetTurnoverRate() float64 {
	if m != nil && m.TurnoverRate != nil {
		return *m.TurnoverRate
	}
	return 0
}

func (m *BasicQot) GetAmplitude() float64 {
	if m != nil && m.Amplitude != nil {
		return *m.Amplitude
	}
	return 0
}

func (m *BasicQot) GetDarkStatus() int32 {
	if m != nil && m.DarkStatus != nil {
		return *m.DarkStatus
	}
	return 0
}

func (m *BasicQot) GetOptionExData() *OptionBasicQotExData {
	if m != nil {
		return m.OptionExData
	}
	return nil
}

type TimeShare struct {
	Time             *string  `protobuf:"bytes,1,req,name=time" json:"time,omitempty"`
	Minute           *int32   `protobuf:"varint,2,req,name=minute" json:"minute,omitempty"`
	IsBlank          *bool    `protobuf:"varint,3,req,name=isBlank" json:"isBlank,omitempty"`
	Price            *float64 `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	LastClosePrice   *float64 `protobuf:"fixed64,5,opt,name=lastClosePrice" json:"lastClosePrice,omitempty"`
	AvgPrice         *float64 `protobuf:"fixed64,6,opt,name=avgPrice" json:"avgPrice,omitempty"`
	Volume           *int64   `protobuf:"varint,7,opt,name=volume" json:"volume,omitempty"`
	Turnover         *float64 `protobuf:"fixed64,8,opt,name=turnover" json:"turnover,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TimeShare) Reset()                    { *m = TimeShare{} }
func (m *TimeShare) String() string            { return proto.CompactTextString(m) }
func (*TimeShare) ProtoMessage()               {}
func (*TimeShare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TimeShare) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *TimeShare) GetMinute() int32 {
	if m != nil && m.Minute != nil {
		return *m.Minute
	}
	return 0
}

func (m *TimeShare) GetIsBlank() bool {
	if m != nil && m.IsBlank != nil {
		return *m.IsBlank
	}
	return false
}

func (m *TimeShare) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *TimeShare) GetLastClosePrice() float64 {
	if m != nil && m.LastClosePrice != nil {
		return *m.LastClosePrice
	}
	return 0
}

func (m *TimeShare) GetAvgPrice() float64 {
	if m != nil && m.AvgPrice != nil {
		return *m.AvgPrice
	}
	return 0
}

func (m *TimeShare) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *TimeShare) GetTurnover() float64 {
	if m != nil && m.Turnover != nil {
		return *m.Turnover
	}
	return 0
}

type SecurityStaticBasic struct {
	Security         *Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	Id               *int64    `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	LotSize          *int32    `protobuf:"varint,3,req,name=lotSize" json:"lotSize,omitempty"`
	SecType          *int32    `protobuf:"varint,4,req,name=secType" json:"secType,omitempty"`
	Name             *string   `protobuf:"bytes,5,req,name=name" json:"name,omitempty"`
	ListTime         *string   `protobuf:"bytes,6,req,name=listTime" json:"listTime,omitempty"`
	Delisting        *bool     `protobuf:"varint,7,opt,name=delisting" json:"delisting,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SecurityStaticBasic) Reset()                    { *m = SecurityStaticBasic{} }
func (m *SecurityStaticBasic) String() string            { return proto.CompactTextString(m) }
func (*SecurityStaticBasic) ProtoMessage()               {}
func (*SecurityStaticBasic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SecurityStaticBasic) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *SecurityStaticBasic) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SecurityStaticBasic) GetLotSize() int32 {
	if m != nil && m.LotSize != nil {
		return *m.LotSize
	}
	return 0
}

func (m *SecurityStaticBasic) GetSecType() int32 {
	if m != nil && m.SecType != nil {
		return *m.SecType
	}
	return 0
}

func (m *SecurityStaticBasic) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SecurityStaticBasic) GetListTime() string {
	if m != nil && m.ListTime != nil {
		return *m.ListTime
	}
	return ""
}

func (m *SecurityStaticBasic) GetDelisting() bool {
	if m != nil && m.Delisting != nil {
		return *m.Delisting
	}
	return false
}

type WarrantStaticExData struct {
	Type             *int32    `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Owner            *Security `protobuf:"bytes,2,req,name=owner" json:"owner,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *WarrantStaticExData) Reset()                    { *m = WarrantStaticExData{} }
func (m *WarrantStaticExData) String() string            { return proto.CompactTextString(m) }
func (*WarrantStaticExData) ProtoMessage()               {}
func (*WarrantStaticExData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WarrantStaticExData) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *WarrantStaticExData) GetOwner() *Security {
	if m != nil {
		return m.Owner
	}
	return nil
}

type OptionStaticExData struct {
	Type             *int32    `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Owner            *Security `protobuf:"bytes,2,req,name=owner" json:"owner,omitempty"`
	StrikeTime       *string   `protobuf:"bytes,3,req,name=strikeTime" json:"strikeTime,omitempty"`
	StrikePrice      *float64  `protobuf:"fixed64,4,req,name=strikePrice" json:"strikePrice,omitempty"`
	Suspend          *bool     `protobuf:"varint,5,req,name=suspend" json:"suspend,omitempty"`
	Market           *string   `protobuf:"bytes,6,req,name=market" json:"market,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *OptionStaticExData) Reset()                    { *m = OptionStaticExData{} }
func (m *OptionStaticExData) String() string            { return proto.CompactTextString(m) }
func (*OptionStaticExData) ProtoMessage()               {}
func (*OptionStaticExData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OptionStaticExData) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *OptionStaticExData) GetOwner() *Security {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OptionStaticExData) GetStrikeTime() string {
	if m != nil && m.StrikeTime != nil {
		return *m.StrikeTime
	}
	return ""
}

func (m *OptionStaticExData) GetStrikePrice() float64 {
	if m != nil && m.StrikePrice != nil {
		return *m.StrikePrice
	}
	return 0
}

func (m *OptionStaticExData) GetSuspend() bool {
	if m != nil && m.Suspend != nil {
		return *m.Suspend
	}
	return false
}

func (m *OptionStaticExData) GetMarket() string {
	if m != nil && m.Market != nil {
		return *m.Market
	}
	return ""
}

type SecurityStaticInfo struct {
	Basic            *SecurityStaticBasic `protobuf:"bytes,1,req,name=basic" json:"basic,omitempty"`
	WarrantExData    *WarrantStaticExData `protobuf:"bytes,2,opt,name=warrantExData" json:"warrantExData,omitempty"`
	OptionExData     *OptionStaticExData  `protobuf:"bytes,3,opt,name=optionExData" json:"optionExData,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SecurityStaticInfo) Reset()                    { *m = SecurityStaticInfo{} }
func (m *SecurityStaticInfo) String() string            { return proto.CompactTextString(m) }
func (*SecurityStaticInfo) ProtoMessage()               {}
func (*SecurityStaticInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SecurityStaticInfo) GetBasic() *SecurityStaticBasic {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *SecurityStaticInfo) GetWarrantExData() *WarrantStaticExData {
	if m != nil {
		return m.WarrantExData
	}
	return nil
}

func (m *SecurityStaticInfo) GetOptionExData() *OptionStaticExData {
	if m != nil {
		return m.OptionExData
	}
	return nil
}

type Broker struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Pos              *int32  `protobuf:"varint,3,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Broker) Reset()                    { *m = Broker{} }
func (m *Broker) String() string            { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()               {}
func (*Broker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Broker) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Broker) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Broker) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type Ticker struct {
	Time             *string  `protobuf:"bytes,1,req,name=time" json:"time,omitempty"`
	Sequence         *int64   `protobuf:"varint,2,req,name=sequence" json:"sequence,omitempty"`
	Dir              *int32   `protobuf:"varint,3,req,name=dir" json:"dir,omitempty"`
	Price            *float64 `protobuf:"fixed64,4,req,name=price" json:"price,omitempty"`
	Volume           *int64   `protobuf:"varint,5,req,name=volume" json:"volume,omitempty"`
	Turnover         *float64 `protobuf:"fixed64,6,req,name=turnover" json:"turnover,omitempty"`
	RecvTime         *float64 `protobuf:"fixed64,7,opt,name=recvTime" json:"recvTime,omitempty"`
	Type             *int32   `protobuf:"varint,8,opt,name=type" json:"type,omitempty"`
	TypeSign         *int32   `protobuf:"varint,9,opt,name=typeSign" json:"typeSign,omitempty"`
	PushDataType     *int32   `protobuf:"varint,10,opt,name=pushDataType" json:"pushDataType,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Ticker) Reset()                    { *m = Ticker{} }
func (m *Ticker) String() string            { return proto.CompactTextString(m) }
func (*Ticker) ProtoMessage()               {}
func (*Ticker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Ticker) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *Ticker) GetSequence() int64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *Ticker) GetDir() int32 {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return 0
}

func (m *Ticker) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Ticker) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *Ticker) GetTurnover() float64 {
	if m != nil && m.Turnover != nil {
		return *m.Turnover
	}
	return 0
}

func (m *Ticker) GetRecvTime() float64 {
	if m != nil && m.RecvTime != nil {
		return *m.RecvTime
	}
	return 0
}

func (m *Ticker) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Ticker) GetTypeSign() int32 {
	if m != nil && m.TypeSign != nil {
		return *m.TypeSign
	}
	return 0
}

func (m *Ticker) GetPushDataType() int32 {
	if m != nil && m.PushDataType != nil {
		return *m.PushDataType
	}
	return 0
}

type OrderBook struct {
	Price            *float64 `protobuf:"fixed64,1,req,name=price" json:"price,omitempty"`
	Volume           *int64   `protobuf:"varint,2,req,name=volume" json:"volume,omitempty"`
	OrederCount      *int32   `protobuf:"varint,3,req,name=orederCount" json:"orederCount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *OrderBook) Reset()                    { *m = OrderBook{} }
func (m *OrderBook) String() string            { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()               {}
func (*OrderBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrderBook) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *OrderBook) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *OrderBook) GetOrederCount() int32 {
	if m != nil && m.OrederCount != nil {
		return *m.OrederCount
	}
	return 0
}

type OrderDetail struct {
	OrderCount       *int32    `protobuf:"varint,1,req,name=orderCount" json:"orderCount,omitempty"`
	OrderVol         []float64 `protobuf:"fixed64,2,rep,name=orderVol" json:"orderVol,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *OrderDetail) Reset()                    { *m = OrderDetail{} }
func (m *OrderDetail) String() string            { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()               {}
func (*OrderDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OrderDetail) GetOrderCount() int32 {
	if m != nil && m.OrderCount != nil {
		return *m.OrderCount
	}
	return 0
}

func (m *OrderDetail) GetOrderVol() []float64 {
	if m != nil {
		return m.OrderVol
	}
	return nil
}

// 持股变动
type ShareHoldingChange struct {
	HolderName       *string  `protobuf:"bytes,1,req,name=holderName" json:"holderName,omitempty"`
	HoldingQty       *float64 `protobuf:"fixed64,2,req,name=holdingQty" json:"holdingQty,omitempty"`
	HoldingRatio     *float64 `protobuf:"fixed64,3,req,name=holdingRatio" json:"holdingRatio,omitempty"`
	ChangeQty        *float64 `protobuf:"fixed64,4,req,name=changeQty" json:"changeQty,omitempty"`
	ChangeRatio      *float64 `protobuf:"fixed64,5,req,name=changeRatio" json:"changeRatio,omitempty"`
	Time             *string  `protobuf:"bytes,6,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ShareHoldingChange) Reset()                    { *m = ShareHoldingChange{} }
func (m *ShareHoldingChange) String() string            { return proto.CompactTextString(m) }
func (*ShareHoldingChange) ProtoMessage()               {}
func (*ShareHoldingChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ShareHoldingChange) GetHolderName() string {
	if m != nil && m.HolderName != nil {
		return *m.HolderName
	}
	return ""
}

func (m *ShareHoldingChange) GetHoldingQty() float64 {
	if m != nil && m.HoldingQty != nil {
		return *m.HoldingQty
	}
	return 0
}

func (m *ShareHoldingChange) GetHoldingRatio() float64 {
	if m != nil && m.HoldingRatio != nil {
		return *m.HoldingRatio
	}
	return 0
}

func (m *ShareHoldingChange) GetChangeQty() float64 {
	if m != nil && m.ChangeQty != nil {
		return *m.ChangeQty
	}
	return 0
}

func (m *ShareHoldingChange) GetChangeRatio() float64 {
	if m != nil && m.ChangeRatio != nil {
		return *m.ChangeRatio
	}
	return 0
}

func (m *ShareHoldingChange) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

type SubInfo struct {
	SubType          *int32      `protobuf:"varint,1,req,name=subType" json:"subType,omitempty"`
	SecurityList     []*Security `protobuf:"bytes,2,rep,name=securityList" json:"securityList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SubInfo) Reset()                    { *m = SubInfo{} }
func (m *SubInfo) String() string            { return proto.CompactTextString(m) }
func (*SubInfo) ProtoMessage()               {}
func (*SubInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SubInfo) GetSubType() int32 {
	if m != nil && m.SubType != nil {
		return *m.SubType
	}
	return 0
}

func (m *SubInfo) GetSecurityList() []*Security {
	if m != nil {
		return m.SecurityList
	}
	return nil
}

type ConnSubInfo struct {
	SubInfoList      []*SubInfo `protobuf:"bytes,1,rep,name=subInfoList" json:"subInfoList,omitempty"`
	UsedQuota        *int32     `protobuf:"varint,2,req,name=usedQuota" json:"usedQuota,omitempty"`
	IsOwnConnData    *bool      `protobuf:"varint,3,req,name=isOwnConnData" json:"isOwnConnData,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ConnSubInfo) Reset()                    { *m = ConnSubInfo{} }
func (m *ConnSubInfo) String() string            { return proto.CompactTextString(m) }
func (*ConnSubInfo) ProtoMessage()               {}
func (*ConnSubInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ConnSubInfo) GetSubInfoList() []*SubInfo {
	if m != nil {
		return m.SubInfoList
	}
	return nil
}

func (m *ConnSubInfo) GetUsedQuota() int32 {
	if m != nil && m.UsedQuota != nil {
		return *m.UsedQuota
	}
	return 0
}

func (m *ConnSubInfo) GetIsOwnConnData() bool {
	if m != nil && m.IsOwnConnData != nil {
		return *m.IsOwnConnData
	}
	return false
}

type PlateInfo struct {
	Plate            *Security `protobuf:"bytes,1,req,name=plate" json:"plate,omitempty"`
	Name             *string   `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	PlateType        *int32    `protobuf:"varint,3,opt,name=plateType" json:"plateType,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PlateInfo) Reset()                    { *m = PlateInfo{} }
func (m *PlateInfo) String() string            { return proto.CompactTextString(m) }
func (*PlateInfo) ProtoMessage()               {}
func (*PlateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PlateInfo) GetPlate() *Security {
	if m != nil {
		return m.Plate
	}
	return nil
}

func (m *PlateInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlateInfo) GetPlateType() int32 {
	if m != nil && m.PlateType != nil {
		return *m.PlateType
	}
	return 0
}

func init() {
	proto.RegisterType((*Security)(nil), "Qot_Common.Security")
	proto.RegisterType((*KLine)(nil), "Qot_Common.KLine")
	proto.RegisterType((*OptionBasicQotExData)(nil), "Qot_Common.OptionBasicQotExData")
	proto.RegisterType((*BasicQot)(nil), "Qot_Common.BasicQot")
	proto.RegisterType((*TimeShare)(nil), "Qot_Common.TimeShare")
	proto.RegisterType((*SecurityStaticBasic)(nil), "Qot_Common.SecurityStaticBasic")
	proto.RegisterType((*WarrantStaticExData)(nil), "Qot_Common.WarrantStaticExData")
	proto.RegisterType((*OptionStaticExData)(nil), "Qot_Common.OptionStaticExData")
	proto.RegisterType((*SecurityStaticInfo)(nil), "Qot_Common.SecurityStaticInfo")
	proto.RegisterType((*Broker)(nil), "Qot_Common.Broker")
	proto.RegisterType((*Ticker)(nil), "Qot_Common.Ticker")
	proto.RegisterType((*OrderBook)(nil), "Qot_Common.OrderBook")
	proto.RegisterType((*OrderDetail)(nil), "Qot_Common.OrderDetail")
	proto.RegisterType((*ShareHoldingChange)(nil), "Qot_Common.ShareHoldingChange")
	proto.RegisterType((*SubInfo)(nil), "Qot_Common.SubInfo")
	proto.RegisterType((*ConnSubInfo)(nil), "Qot_Common.ConnSubInfo")
	proto.RegisterType((*PlateInfo)(nil), "Qot_Common.PlateInfo")
	proto.RegisterEnum("Qot_Common.QotMarket", QotMarket_name, QotMarket_value)
	proto.RegisterEnum("Qot_Common.SecurityType", SecurityType_name, SecurityType_value)
	proto.RegisterEnum("Qot_Common.PlateSetType", PlateSetType_name, PlateSetType_value)
	proto.RegisterEnum("Qot_Common.WarrantType", WarrantType_name, WarrantType_value)
	proto.RegisterEnum("Qot_Common.OptionType", OptionType_name, OptionType_value)
	proto.RegisterEnum("Qot_Common.QotMarketState", QotMarketState_name, QotMarketState_value)
	proto.RegisterEnum("Qot_Common.RehabType", RehabType_name, RehabType_value)
	proto.RegisterEnum("Qot_Common.KLType", KLType_name, KLType_value)
	proto.RegisterEnum("Qot_Common.KLFields", KLFields_name, KLFields_value)
	proto.RegisterEnum("Qot_Common.SubType", SubType_name, SubType_value)
	proto.RegisterEnum("Qot_Common.TickerDirection", TickerDirection_name, TickerDirection_value)
	proto.RegisterEnum("Qot_Common.TickerType", TickerType_name, TickerType_value)
	proto.RegisterEnum("Qot_Common.DarkStatus", DarkStatus_name, DarkStatus_value)
	proto.RegisterEnum("Qot_Common.HolderCategory", HolderCategory_name, HolderCategory_value)
	proto.RegisterEnum("Qot_Common.PushDataType", PushDataType_name, PushDataType_value)
}

func init() { proto.RegisterFile("Qot_Common/Qot_Common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4b, 0x6f, 0x23, 0xc7,
	0xf1, 0xf7, 0x0c, 0x1f, 0x22, 0x8b, 0x7a, 0xb4, 0x5a, 0x8f, 0xa5, 0x65, 0x79, 0x4d, 0xd3, 0xfe,
	0xfb, 0xbf, 0x20, 0x02, 0xc7, 0x6b, 0x63, 0x9d, 0x9c, 0x82, 0x2c, 0xa9, 0x15, 0xb4, 0x58, 0x3d,
	0x87, 0xb2, 0x8d, 0x24, 0x08, 0x16, 0xbd, 0x9c, 0x36, 0x39, 0xd0, 0x68, 0x9a, 0xee, 0xe9, 0x91,
	0x56, 0x01, 0x0c, 0xd8, 0x48, 0x80, 0x04, 0xf9, 0x2a, 0xb9, 0xe4, 0x90, 0x6f, 0x90, 0x4b, 0x0e,
	0x39, 0x07, 0xc8, 0xc1, 0xc8, 0xa7, 0xc8, 0x3d, 0xa8, 0xee, 0x79, 0xf4, 0x0c, 0xa9, 0x3d, 0x04,
	0xb9, 0x75, 0xfd, 0xaa, 0xfa, 0x55, 0xf5, 0xab, 0xea, 0x9a, 0x81, 0x77, 0x2e, 0x84, 0x7a, 0x39,
	0x12, 0xd7, 0xd7, 0x22, 0xfa, 0x71, 0x31, 0xfc, 0x78, 0x2e, 0x85, 0x12, 0x14, 0x0a, 0x64, 0x6f,
	0x2b, 0x35, 0xb2, 0x0d, 0xfa, 0x9f, 0x43, 0x6b, 0xcc, 0x27, 0x89, 0x0c, 0xd4, 0x1d, 0xdd, 0x85,
	0xe6, 0x35, 0x93, 0x57, 0x5c, 0x75, 0x9d, 0x9e, 0xfb, 0xa8, 0xe1, 0xa5, 0x12, 0xa5, 0x50, 0x9f,
	0x08, 0x9f, 0x77, 0xdd, 0x9e, 0xfb, 0xa8, 0xed, 0xe9, 0x71, 0xff, 0x07, 0x17, 0x1a, 0x2f, 0x8e,
	0x83, 0x88, 0xa3, 0x56, 0x05, 0xd7, 0x5c, 0xcf, 0x69, 0x7b, 0x7a, 0x4c, 0xbb, 0xb0, 0x12, 0xc4,
	0xc3, 0x90, 0x45, 0x57, 0x7a, 0x52, 0xcb, 0xcb, 0x44, 0xba, 0x0f, 0xed, 0x59, 0x30, 0x9d, 0x9d,
	0xcb, 0x60, 0xc2, 0xbb, 0xb5, 0x9e, 0xf3, 0xc8, 0xf1, 0x0a, 0x00, 0xb5, 0x62, 0xce, 0x23, 0xa3,
	0xad, 0x1b, 0x6d, 0x0e, 0xd0, 0x3d, 0x68, 0x85, 0xe2, 0xd6, 0x28, 0x1b, 0x5a, 0x99, 0xcb, 0xf4,
	0x21, 0xc0, 0x24, 0x14, 0x31, 0x37, 0xda, 0xa6, 0xd6, 0x5a, 0x08, 0xfd, 0x08, 0xd6, 0x43, 0x16,
	0xab, 0x51, 0x61, 0xb3, 0xa2, 0x6d, 0x2a, 0x28, 0xfa, 0xe0, 0x46, 0x84, 0xc9, 0x35, 0xef, 0xb6,
	0x7a, 0xce, 0xa3, 0x9a, 0x97, 0x4a, 0xb8, 0xb7, 0x4a, 0x64, 0x24, 0x6e, 0xb8, 0xec, 0xb6, 0xcd,
	0xde, 0x99, 0x4c, 0xfb, 0xb0, 0x9a, 0x8d, 0x3d, 0xa6, 0x78, 0x17, 0xb4, 0xbe, 0x84, 0xd1, 0x75,
	0x70, 0xe7, 0xbc, 0xdb, 0xd1, 0x1a, 0x77, 0x6e, 0xce, 0x3b, 0x63, 0xd1, 0x94, 0xeb, 0x19, 0xab,
	0xe9, 0x79, 0x73, 0xa4, 0xff, 0x67, 0x17, 0xb6, 0xcf, 0xe6, 0x2a, 0x10, 0xd1, 0x90, 0xc5, 0xc1,
	0xe4, 0x42, 0xa8, 0x67, 0xaf, 0x0f, 0x98, 0x62, 0xb4, 0x07, 0x9d, 0x58, 0xc9, 0xe0, 0x2a, 0xbd,
	0x05, 0x7a, 0xdd, 0xf1, 0x6c, 0x08, 0x8f, 0x33, 0x11, 0x91, 0x92, 0x6c, 0xa2, 0xc6, 0xc1, 0x6f,
	0x4c, 0xd8, 0x1a, 0x5e, 0x09, 0x43, 0x1b, 0xf4, 0xeb, 0xf3, 0x48, 0x71, 0xc9, 0x63, 0xd5, 0xad,
	0x19, 0x1b, 0x1b, 0xa3, 0x3f, 0x82, 0xcd, 0xe0, 0x7a, 0x1e, 0x06, 0xdc, 0xff, 0x52, 0x84, 0x4c,
	0x05, 0x61, 0xa0, 0xee, 0xba, 0x75, 0xbd, 0xdf, 0xa2, 0x02, 0x43, 0x3e, 0x97, 0xfc, 0x3a, 0x48,
	0xae, 0xbb, 0x0d, 0x6d, 0x93, 0x89, 0x74, 0x1b, 0x1a, 0x3e, 0x0f, 0x15, 0xeb, 0x36, 0x35, 0x6e,
	0x04, 0x44, 0xa7, 0xec, 0xfa, 0x9a, 0x75, 0x57, 0x0c, 0xaa, 0x05, 0x24, 0xd3, 0x0d, 0x9f, 0xb2,
	0x6e, 0x4b, 0x83, 0x7a, 0x8c, 0x96, 0x6a, 0xc6, 0x15, 0xeb, 0xb6, 0x8d, 0xa5, 0x16, 0x28, 0x81,
	0x9a, 0x9c, 0x89, 0x2e, 0x68, 0x0c, 0x87, 0xfd, 0xbf, 0xd4, 0xa1, 0x95, 0x39, 0x8b, 0x7e, 0x02,
	0xad, 0x38, 0xe5, 0xb5, 0xf6, 0x51, 0xe7, 0xd3, 0xed, 0x8f, 0xad, 0xec, 0xc8, 0x38, 0xef, 0xe5,
	0x56, 0xe8, 0xd8, 0x20, 0x1e, 0x27, 0xf1, 0x9c, 0x47, 0x3e, 0xf7, 0x53, 0xde, 0xda, 0x90, 0xe6,
	0x5f, 0x10, 0xab, 0x4b, 0x64, 0x7b, 0x4d, 0xb3, 0x3d, 0x97, 0x71, 0xf6, 0x1c, 0xbd, 0x3f, 0x9e,
	0x4b, 0xce, 0xfc, 0xd4, 0x4d, 0x36, 0x84, 0x11, 0x4f, 0xe6, 0x3e, 0x53, 0x5c, 0xcf, 0x6f, 0xe8,
	0xf9, 0x16, 0x52, 0xce, 0x0c, 0xe3, 0xaa, 0xfb, 0x32, 0xc3, 0xb8, 0xec, 0x9e, 0xcc, 0x30, 0xae,
	0x2b, 0x32, 0x63, 0x0f, 0x5a, 0x93, 0x44, 0x1a, 0x9d, 0xf1, 0x60, 0x2e, 0x2f, 0xc9, 0x0a, 0xe3,
	0xcf, 0xfb, 0xb3, 0xa2, 0xd3, 0x73, 0xef, 0xc9, 0x8a, 0x55, 0xb3, 0xf6, 0xbd, 0x59, 0xb1, 0xa6,
	0xf5, 0xe5, 0xac, 0xd8, 0x87, 0x36, 0x43, 0x26, 0xa9, 0xc4, 0xe7, 0xdd, 0x75, 0x73, 0xab, 0x1c,
	0x40, 0x8f, 0xf9, 0x4c, 0x5e, 0x8d, 0x15, 0x53, 0x49, 0xdc, 0xdd, 0xe8, 0x39, 0x8f, 0x1a, 0x9e,
	0x85, 0xd0, 0x03, 0x24, 0x31, 0xa6, 0x88, 0x49, 0x8d, 0x2e, 0xe9, 0x39, 0x8f, 0x3a, 0x9f, 0xf6,
	0xec, 0x38, 0x2f, 0x4b, 0x21, 0xaf, 0x34, 0xab, 0xff, 0x2f, 0x07, 0xda, 0x18, 0x80, 0xf1, 0x8c,
	0xc9, 0xe5, 0xd5, 0x0c, 0xeb, 0x62, 0x10, 0x25, 0x2a, 0x4b, 0xa5, 0x54, 0xb2, 0xab, 0x5c, 0xad,
	0x5c, 0xe5, 0xb6, 0xa1, 0x31, 0xb7, 0x6a, 0x98, 0x11, 0x96, 0x78, 0xbb, 0xb1, 0xb4, 0x06, 0xed,
	0x41, 0x8b, 0xdd, 0x4c, 0xed, 0x4a, 0x96, 0xcb, 0x56, 0x24, 0x56, 0xee, 0xad, 0x4f, 0xad, 0x72,
	0x7d, 0xea, 0xff, 0xd3, 0x81, 0xad, 0x8c, 0xf0, 0xe8, 0xba, 0x60, 0xa2, 0x1d, 0xf2, 0x5f, 0xe4,
	0xc8, 0x3a, 0xb8, 0x81, 0x49, 0x8d, 0x9a, 0xe7, 0x06, 0x3e, 0x7a, 0x20, 0x14, 0xa6, 0xca, 0x98,
	0x0a, 0x92, 0x89, 0xa8, 0x89, 0xf9, 0xe4, 0xf2, 0x6e, 0xce, 0x75, 0x2e, 0x34, 0xbc, 0x4c, 0x44,
	0x0f, 0x47, 0x2c, 0xcf, 0x00, 0x3d, 0x2e, 0x65, 0x56, 0xb3, 0x92, 0x59, 0xfb, 0xd0, 0xf6, 0x39,
	0x4a, 0x41, 0x34, 0xd5, 0x97, 0x6e, 0x79, 0x05, 0xd0, 0xff, 0x02, 0xb6, 0xbe, 0x62, 0x52, 0xb2,
	0x48, 0x99, 0x9b, 0xa5, 0x55, 0x12, 0xc3, 0x88, 0x7b, 0x9b, 0x87, 0x4c, 0x8f, 0xe9, 0x00, 0x1a,
	0xe2, 0x36, 0xe2, 0x52, 0x9f, 0xff, 0xbe, 0xbb, 0x1a, 0x93, 0xfe, 0xdf, 0x1c, 0xa0, 0x86, 0x3b,
	0xff, 0xcb, 0x65, 0x91, 0xd1, 0xa6, 0x52, 0x5b, 0x35, 0xc4, 0x42, 0xaa, 0xc5, 0xbd, 0xbe, 0x58,
	0xdc, 0xd1, 0xaf, 0xa6, 0x20, 0x69, 0x07, 0xb6, 0xbc, 0x4c, 0xb4, 0x5e, 0x6f, 0xe3, 0xc1, 0x54,
	0xea, 0xff, 0xc3, 0x01, 0x5a, 0x8e, 0xfe, 0xf3, 0xe8, 0x6b, 0x41, 0x9f, 0x40, 0xe3, 0x15, 0xb2,
	0x20, 0x8d, 0xfc, 0x7b, 0xcb, 0x8e, 0x6d, 0x91, 0xc5, 0x33, 0xd6, 0xf4, 0x19, 0xac, 0xdd, 0x1a,
	0x7f, 0xa7, 0x49, 0xe7, 0xea, 0xa4, 0x2b, 0x4d, 0x5f, 0x12, 0x10, 0xaf, 0x3c, 0x8b, 0x0e, 0x2b,
	0xa9, 0x5b, 0xd3, 0xab, 0x3c, 0x5c, 0x4c, 0xdd, 0xd2, 0x22, 0xe5, 0xc4, 0xfd, 0x19, 0x34, 0x87,
	0x52, 0x5c, 0x71, 0x99, 0xd2, 0xd2, 0xc9, 0x69, 0x99, 0x51, 0xcc, 0xb5, 0x28, 0x46, 0xa0, 0x36,
	0x17, 0x71, 0x4a, 0x53, 0x1c, 0xf6, 0x7f, 0xe7, 0x42, 0xf3, 0x32, 0x98, 0xe0, 0x02, 0xcb, 0xb2,
	0x7e, 0x0f, 0xb3, 0xe3, 0x9b, 0x84, 0x47, 0x13, 0x9e, 0x32, 0x3e, 0x97, 0x71, 0x31, 0x3f, 0x90,
	0xd9, 0x62, 0x7e, 0x20, 0xed, 0x8c, 0x77, 0x8b, 0x8c, 0x2f, 0xb2, 0xb5, 0x71, 0x6f, 0xdd, 0x6c,
	0x56, 0xea, 0xe6, 0x1e, 0xb4, 0x24, 0x9f, 0xdc, 0x68, 0x86, 0x98, 0x1e, 0x25, 0x97, 0x73, 0xfe,
	0xb5, 0x74, 0x2d, 0x34, 0xfc, 0xc3, 0xb5, 0xee, 0xe6, 0x7c, 0x1c, 0x4c, 0x23, 0xdd, 0x99, 0x34,
	0xbc, 0x5c, 0xc6, 0x1a, 0x3c, 0x4f, 0xe2, 0x19, 0xba, 0x4b, 0xa7, 0x22, 0x68, 0x7d, 0x09, 0xeb,
	0xff, 0x0a, 0xda, 0x67, 0xd2, 0xe7, 0x72, 0x28, 0x84, 0x55, 0xb8, 0x9c, 0xe5, 0xd7, 0x70, 0x4b,
	0xd7, 0xe8, 0x41, 0x47, 0x48, 0xee, 0x73, 0x39, 0x12, 0x49, 0x94, 0x35, 0x11, 0x36, 0xd4, 0x7f,
	0x0e, 0x1d, 0xbd, 0xf8, 0x01, 0x57, 0x2c, 0x08, 0x91, 0xff, 0x42, 0xe6, 0xf6, 0x26, 0x8b, 0x2c,
	0x04, 0xef, 0xa2, 0xa5, 0x2f, 0x45, 0xd8, 0x75, 0x7b, 0x35, 0xbc, 0x7b, 0x26, 0xf7, 0xff, 0x8e,
	0x3c, 0xc6, 0x1a, 0x7d, 0x24, 0x42, 0x3f, 0x88, 0xa6, 0x23, 0xdd, 0x2c, 0xe1, 0x92, 0x33, 0x11,
	0xfa, 0x5c, 0x9e, 0xb2, 0x3c, 0x80, 0x16, 0x92, 0xe9, 0x83, 0x68, 0x7a, 0xa1, 0xee, 0xf4, 0xf9,
	0x1d, 0xcf, 0x42, 0xd0, 0x45, 0xa9, 0xe4, 0x31, 0x15, 0x08, 0x7d, 0x09, 0xc7, 0x2b, 0x61, 0x58,
	0x82, 0x4c, 0x6b, 0x76, 0x91, 0x77, 0x40, 0x05, 0x80, 0x5e, 0xc8, 0x1b, 0xb7, 0x40, 0xa4, 0xdd,
	0x8f, 0x0d, 0xe5, 0xf4, 0x6a, 0x16, 0xf4, 0xea, 0xff, 0x1a, 0x56, 0xc6, 0xc9, 0x2b, 0x9d, 0x8a,
	0x3a, 0xa7, 0x5f, 0x5d, 0x16, 0x85, 0x25, 0x13, 0xe9, 0x4f, 0x61, 0x35, 0xab, 0xbd, 0xc7, 0x41,
	0xac, 0xb4, 0x4f, 0xee, 0x2b, 0x31, 0x25, 0xcb, 0xfe, 0x1f, 0x1c, 0xe8, 0x8c, 0x44, 0x14, 0x65,
	0x7b, 0x3c, 0x81, 0x4e, 0x6c, 0x86, 0x7a, 0x21, 0x47, 0x2f, 0xb4, 0x55, 0x5a, 0xc8, 0xa8, 0x3d,
	0xdb, 0x0e, 0x6f, 0x9e, 0xc4, 0xdc, 0xbf, 0x48, 0x84, 0x4e, 0x75, 0x3c, 0x5c, 0x01, 0xd0, 0x0f,
	0x61, 0x2d, 0x88, 0xcf, 0x6e, 0x23, 0xdc, 0x28, 0x4d, 0x63, 0x2c, 0x49, 0x65, 0xb0, 0x1f, 0x40,
	0xfb, 0x3c, 0x64, 0x8a, 0xeb, 0x73, 0x0c, 0xa0, 0x31, 0x47, 0xe1, 0x8d, 0x0f, 0x8e, 0x31, 0x59,
	0x9a, 0xc6, 0xfb, 0xd0, 0xd6, 0x4a, 0xed, 0xad, 0x9a, 0xa6, 0x73, 0x01, 0x0c, 0xfe, 0xe4, 0x40,
	0xfb, 0x42, 0xa8, 0x13, 0xf3, 0xdd, 0xb2, 0x03, 0x9b, 0xb9, 0xf0, 0xf2, 0x8b, 0xe8, 0x2a, 0x12,
	0xb7, 0x11, 0x79, 0x8b, 0xbe, 0x0d, 0x3b, 0x05, 0x7c, 0xf4, 0xe2, 0x65, 0xb6, 0x2d, 0x71, 0xe8,
	0x03, 0xd8, 0x2a, 0xa9, 0x0e, 0x13, 0x95, 0x48, 0x4e, 0xdc, 0xf2, 0x9c, 0x2f, 0xc6, 0xc5, 0x9c,
	0x0e, 0x7d, 0x07, 0x1e, 0x14, 0xaa, 0xd1, 0xe9, 0xf8, 0xa8, 0x50, 0xee, 0x2c, 0x28, 0x7f, 0x59,
	0x28, 0x77, 0x07, 0xdf, 0xbb, 0xb0, 0x9a, 0x89, 0x3a, 0xdc, 0x5d, 0xd8, 0xb6, 0x65, 0xeb, 0xcc,
	0x3b, 0xb0, 0x59, 0xd2, 0x0c, 0x45, 0xe4, 0x13, 0x67, 0x11, 0xbe, 0x95, 0x8a, 0xb8, 0x0b, 0xf0,
	0xb3, 0x6f, 0xd4, 0x1d, 0xa9, 0xd1, 0xdd, 0xe2, 0x21, 0xd0, 0xf0, 0xa5, 0x4c, 0x62, 0x45, 0xea,
	0x0b, 0xdb, 0xa6, 0xf5, 0x9b, 0x34, 0x16, 0x66, 0x3c, 0x8f, 0x7c, 0xfe, 0x9a, 0x34, 0x17, 0x70,
	0x1d, 0x5f, 0xb2, 0xb2, 0xb0, 0xf1, 0x81, 0xbc, 0x51, 0xa4, 0x85, 0xde, 0x5b, 0x34, 0x1f, 0x73,
	0x45, 0xda, 0x83, 0x3f, 0x3a, 0xb0, 0x9a, 0x89, 0xda, 0x07, 0xdb, 0x40, 0x6c, 0xf9, 0xe5, 0xd3,
	0x30, 0x34, 0x31, 0x2b, 0xa1, 0xcf, 0x23, 0x3f, 0x89, 0x95, 0x4c, 0x63, 0x56, 0x52, 0x79, 0x7c,
	0x1a, 0x88, 0x88, 0xb8, 0x78, 0xad, 0x92, 0x62, 0x24, 0xa2, 0x09, 0x9f, 0x2b, 0xe3, 0x88, 0x92,
	0xe6, 0x4c, 0xcd, 0xb8, 0x24, 0xf5, 0xc1, 0xb7, 0xd0, 0x49, 0xef, 0xae, 0x8f, 0xf2, 0x20, 0xef,
	0x2d, 0x2a, 0xd1, 0xd8, 0x82, 0x0d, 0x5b, 0x31, 0x4c, 0xf0, 0x1c, 0xdb, 0x40, 0x6c, 0x70, 0xcc,
	0xc3, 0x90, 0xb8, 0x55, 0x74, 0x98, 0x84, 0x21, 0xa9, 0x2d, 0xa0, 0x9c, 0xe1, 0xf6, 0x27, 0x00,
	0xe6, 0xd1, 0xd3, 0xbb, 0xef, 0x66, 0x1d, 0xc8, 0xe2, 0xe6, 0x16, 0x3e, 0x62, 0x61, 0x48, 0x1c,
	0x4a, 0x61, 0xdd, 0x02, 0xcf, 0x13, 0x45, 0xdc, 0xc1, 0x5f, 0xeb, 0xb0, 0x9e, 0x93, 0x0f, 0xdf,
	0x51, 0x5e, 0xe2, 0xb7, 0x46, 0x5e, 0x9e, 0x8a, 0x88, 0x93, 0xb7, 0xe8, 0x1e, 0xec, 0x56, 0x14,
	0x4f, 0x93, 0x09, 0xae, 0x47, 0x1c, 0xfa, 0x10, 0xf6, 0x2a, 0xba, 0xaf, 0x58, 0x80, 0xcd, 0xd7,
	0xd9, 0x9c, 0xa3, 0x9f, 0x17, 0xe7, 0x9e, 0x08, 0x19, 0x05, 0xd1, 0x94, 0xd4, 0x96, 0x6c, 0xe8,
	0x71, 0xcd, 0xb9, 0x7d, 0xe8, 0x56, 0x37, 0xfc, 0x5a, 0x71, 0x19, 0x09, 0x11, 0x91, 0x46, 0x29,
	0xdd, 0x8c, 0x56, 0xb7, 0xc7, 0x3e, 0x69, 0xd2, 0xf7, 0xe1, 0xdd, 0x8a, 0xea, 0x5c, 0x72, 0x23,
	0x0e, 0xf9, 0x34, 0x88, 0x48, 0x8b, 0xbe, 0xa7, 0xff, 0x89, 0x2c, 0x35, 0x79, 0x16, 0xf9, 0xa4,
	0x4d, 0xfb, 0xf0, 0x70, 0xd9, 0xe6, 0x47, 0x22, 0x91, 0xb1, 0x59, 0x04, 0x68, 0x0f, 0xf6, 0xef,
	0xb5, 0xc1, 0x55, 0x3a, 0x4b, 0xae, 0x70, 0x1a, 0x4c, 0x67, 0x4a, 0x7b, 0x65, 0xad, 0x94, 0xf9,
	0x96, 0x16, 0xa7, 0xae, 0x2f, 0x59, 0xdc, 0x54, 0x9a, 0x03, 0x76, 0xa7, 0xa7, 0x6f, 0x2c, 0xb9,
	0x66, 0x6e, 0x31, 0x94, 0x9c, 0x5d, 0x11, 0xf2, 0x26, 0x13, 0xed, 0x2d, 0xb2, 0x49, 0xff, 0x1f,
	0x3e, 0xb8, 0xcf, 0x04, 0x63, 0x78, 0x28, 0xa4, 0xde, 0x8e, 0x62, 0xae, 0x54, 0x0c, 0x8f, 0xae,
	0x46, 0x2c, 0x26, 0x5b, 0x83, 0x53, 0x68, 0x7b, 0x7c, 0xc6, 0x5e, 0xa5, 0xbd, 0xfb, 0x7a, 0x2e,
	0x64, 0xd4, 0xd9, 0x81, 0xcd, 0x02, 0x3b, 0x14, 0xf2, 0x96, 0x49, 0x2c, 0x4d, 0xbb, 0x40, 0x0b,
	0x78, 0xc8, 0x26, 0x57, 0x1a, 0x77, 0x07, 0x3f, 0x38, 0xd0, 0x7c, 0x71, 0x9c, 0xad, 0x66, 0x46,
	0x16, 0xbb, 0x37, 0xa0, 0x93, 0x62, 0x8f, 0x4f, 0x02, 0x64, 0xdf, 0x3a, 0x40, 0x0a, 0x1c, 0xb0,
	0x3b, 0xe2, 0x5a, 0x06, 0x5f, 0x71, 0x7e, 0x45, 0x6a, 0x94, 0xc0, 0x6a, 0x0a, 0x9c, 0x88, 0x48,
	0xcd, 0x48, 0xdd, 0x32, 0xf9, 0x05, 0x26, 0x56, 0xc3, 0x02, 0x9e, 0xe0, 0xa2, 0x4d, 0x6b, 0xce,
	0x63, 0x8d, 0xac, 0x58, 0xc8, 0x67, 0x9f, 0x9c, 0x68, 0x16, 0x15, 0xc8, 0xe7, 0x1a, 0x69, 0x5b,
	0xcb, 0x7c, 0x76, 0xa2, 0x39, 0x52, 0x5c, 0xe0, 0x22, 0x61, 0x52, 0x71, 0x49, 0x3a, 0x83, 0x7f,
	0x3b, 0xd0, 0x7a, 0x71, 0x7c, 0x18, 0xf0, 0xd0, 0x8f, 0xe9, 0x26, 0xac, 0x65, 0xe3, 0xcc, 0x5d,
	0x36, 0x74, 0x14, 0x4c, 0x67, 0xc4, 0x29, 0x41, 0x69, 0x4e, 0xe9, 0xcd, 0x53, 0xe8, 0x58, 0xdc,
	0x92, 0xba, 0xd9, 0x2b, 0x45, 0x4c, 0x78, 0x5b, 0xe8, 0xe3, 0xc2, 0x2a, 0xfb, 0x86, 0x24, 0x04,
	0x4b, 0x44, 0x8e, 0x7f, 0xa9, 0x5b, 0x35, 0xd2, 0xc3, 0x38, 0xe5, 0xe0, 0x65, 0xda, 0x6c, 0x92,
	0x9f, 0xd3, 0x3d, 0xd8, 0x59, 0x80, 0xf1, 0xdb, 0x9c, 0x7c, 0xe7, 0x50, 0x82, 0x17, 0x4e, 0x75,
	0xe7, 0xcf, 0xc8, 0x77, 0x58, 0x53, 0xb7, 0x8a, 0x53, 0xe4, 0x7f, 0xab, 0xc8, 0x77, 0xf5, 0xc1,
	0x6f, 0x6b, 0xba, 0xa1, 0xd1, 0x81, 0x25, 0xb0, 0x9a, 0x0e, 0xad, 0x5b, 0x67, 0x88, 0xfe, 0x9c,
	0x48, 0xdf, 0xae, 0x14, 0xca, 0xfb, 0x4f, 0xe2, 0xe2, 0x3d, 0x33, 0xd8, 0x34, 0xe7, 0xa4, 0x8e,
	0x1c, 0xc8, 0x30, 0xef, 0x92, 0x34, 0x6c, 0x9b, 0x17, 0xc7, 0x9a, 0x17, 0x4d, 0xbc, 0xb3, 0x85,
	0xa5, 0x51, 0xdd, 0x06, 0x62, 0x81, 0x26, 0xd6, 0xad, 0x0a, 0xfa, 0x59, 0x1a, 0xdd, 0x32, 0x6a,
	0x62, 0x0e, 0x95, 0x65, 0x35, 0x27, 0x3b, 0x15, 0x50, 0xf3, 0x70, 0xb5, 0x32, 0xdf, 0x70, 0x71,
	0xcd, 0x3e, 0xaa, 0xf9, 0x58, 0x21, 0xeb, 0xfa, 0xf5, 0x2c, 0x2c, 0x2f, 0x12, 0xc9, 0x90, 0x3a,
	0x1b, 0x95, 0x65, 0x35, 0x77, 0x49, 0x05, 0xd4, 0xc4, 0xdb, 0xc4, 0xb2, 0x5a, 0xf2, 0x9d, 0x69,
	0xaf, 0x09, 0x1d, 0x7c, 0x0b, 0x1b, 0xc6, 0x6b, 0x07, 0x81, 0xe4, 0xba, 0x80, 0x63, 0x21, 0xaa,
	0x40, 0x56, 0xba, 0x3d, 0x80, 0xad, 0xaa, 0x72, 0x18, 0xf8, 0xe6, 0x55, 0xad, 0x2a, 0x9e, 0xc6,
	0x18, 0x9f, 0x25, 0xcb, 0x9d, 0xf2, 0x44, 0x49, 0x16, 0x92, 0xda, 0xe0, 0xf7, 0x2b, 0x00, 0x46,
	0x9b, 0x3d, 0x61, 0x85, 0x64, 0xed, 0xda, 0x85, 0x6d, 0x0b, 0x7f, 0x9a, 0x28, 0x71, 0xcd, 0xd4,
	0x04, 0x53, 0x61, 0x2b, 0x3b, 0xbf, 0xd6, 0x1c, 0x23, 0xb7, 0x5c, 0x2c, 0xb4, 0x16, 0x88, 0x8c,
	0x2a, 0xa6, 0xd4, 0xe8, 0xbb, 0xf0, 0xb6, 0xa5, 0xd5, 0x7f, 0x2f, 0x0b, 0x75, 0x1d, 0xab, 0x64,
	0x55, 0x5d, 0x5e, 0xa1, 0x81, 0x4c, 0xb4, 0x4c, 0xce, 0x7c, 0xff, 0x58, 0x28, 0xd3, 0xe4, 0x94,
	0x4e, 0x69, 0xde, 0xc3, 0x95, 0xca, 0x19, 0x87, 0x49, 0x78, 0x65, 0x38, 0x65, 0x81, 0x23, 0xc9,
	0xe2, 0x19, 0x69, 0xe3, 0xd3, 0x58, 0x42, 0x45, 0x1c, 0x9b, 0x1a, 0x4b, 0xa0, 0xf0, 0x70, 0xbe,
	0xcc, 0x58, 0x84, 0xf8, 0xae, 0x94, 0x27, 0x1d, 0x4a, 0xce, 0xcf, 0xa2, 0xa1, 0xc0, 0xea, 0xb9,
	0x5a, 0x78, 0xdf, 0x24, 0x43, 0x12, 0xf2, 0xc7, 0x9f, 0xfe, 0xe4, 0x4c, 0x3e, 0x7e, 0xf2, 0x84,
	0xac, 0x55, 0xce, 0x70, 0xc0, 0x43, 0x76, 0x47, 0xd6, 0xe9, 0xff, 0xc1, 0xfb, 0x16, 0x6a, 0xb6,
	0x1f, 0x71, 0xf4, 0x43, 0xf1, 0xcb, 0x89, 0x6c, 0x54, 0x6e, 0x7b, 0xca, 0x5f, 0x2b, 0xcc, 0x2b,
	0x82, 0x6f, 0xe5, 0x3d, 0xd3, 0xb1, 0x54, 0xe1, 0x2b, 0xbf, 0x59, 0xb1, 0x39, 0x97, 0x81, 0x90,
	0x1e, 0xff, 0x9a, 0x4b, 0xfc, 0x56, 0x36, 0xeb, 0x53, 0xfa, 0x21, 0xf4, 0xde, 0xb0, 0x8e, 0xb1,
	0xda, 0xaa, 0x84, 0x02, 0x7b, 0x28, 0x2e, 0xc9, 0x36, 0x16, 0x14, 0x0b, 0xbe, 0x24, 0x3b, 0xf4,
	0x03, 0x78, 0xcf, 0x42, 0x9e, 0xbd, 0x56, 0xfa, 0x17, 0xed, 0xa5, 0x64, 0xf8, 0xd5, 0xa6, 0x1f,
	0x69, 0xb2, 0x8b, 0x6d, 0x84, 0xed, 0x7e, 0x11, 0x61, 0xd7, 0xc2, 0x23, 0x45, 0x1e, 0x54, 0x1c,
	0xf9, 0xf4, 0x86, 0x4b, 0x36, 0x4d, 0xcf, 0xda, 0xad, 0xf8, 0xe2, 0xec, 0x72, 0xa4, 0x23, 0xf3,
	0x36, 0x3e, 0xdb, 0x0b, 0x44, 0xb1, 0x83, 0xba, 0x57, 0x61, 0xdb, 0x01, 0x97, 0xc1, 0x0d, 0x53,
	0xc1, 0x0d, 0x0f, 0xef, 0xf4, 0xda, 0x3e, 0x79, 0x07, 0xdb, 0x29, 0x3b, 0x84, 0x3c, 0x75, 0x63,
	0xaa, 0xdf, 0xaf, 0xb0, 0x1d, 0x63, 0x54, 0x68, 0xdf, 0xa5, 0x1f, 0x41, 0xbf, 0x74, 0xa5, 0xeb,
	0xb9, 0xe4, 0x33, 0x1e, 0xc5, 0xc1, 0x0d, 0xd7, 0x01, 0x37, 0x57, 0x78, 0x88, 0xbd, 0xe4, 0x41,
	0xf1, 0xa7, 0x74, 0x0b, 0x36, 0x0a, 0x29, 0xab, 0xc9, 0xbb, 0x40, 0x2d, 0x30, 0x75, 0x9d, 0xe9,
	0x25, 0x2d, 0x1c, 0x1b, 0x16, 0x77, 0xf0, 0xbd, 0x03, 0xeb, 0x47, 0xfa, 0xa3, 0x7a, 0xc4, 0x14,
	0x9f, 0x0a, 0x79, 0x87, 0xce, 0x2d, 0x23, 0x69, 0x82, 0x9b, 0x6e, 0xbd, 0xa2, 0x7a, 0x3a, 0xe5,
	0xd1, 0x24, 0xed, 0xd6, 0x2b, 0xaa, 0xc3, 0x04, 0x77, 0x40, 0xdf, 0x56, 0x14, 0x63, 0x1e, 0x05,
	0x42, 0x9e, 0xb0, 0x88, 0x4d, 0xb9, 0x24, 0xb5, 0xc1, 0x0d, 0xac, 0x9e, 0x5b, 0x3f, 0x2e, 0x74,
	0xe3, 0x6f, 0xc9, 0xa5, 0xed, 0x4b, 0x0a, 0x8f, 0xb3, 0x10, 0xbf, 0xb9, 0x89, 0x83, 0xb9, 0x55,
	0x52, 0x0d, 0xef, 0x0e, 0x82, 0x18, 0xbf, 0x54, 0x89, 0xab, 0xbf, 0x0a, 0x6c, 0xdd, 0x88, 0x4d,
	0x66, 0x9c, 0xd4, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x60, 0x24, 0xcf, 0x50, 0x61, 0x1b, 0x00,
	0x00,
}
