// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetHoldingChangeList/Qot_GetHoldingChangeList.proto

/*
Package Qot_GetHoldingChangeList is a generated protocol buffer package.

It is generated from these files:
	Qot_GetHoldingChangeList/Qot_GetHoldingChangeList.proto

It has these top-level messages:
	C2S
	S2C
	Request
	Response
*/
package Qot_GetHoldingChangeList

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "futugg/pb/Common"
import Qot_Common "futugg/pb/Qot_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Security       *Qot_Common.Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	HolderCategory *int32               `protobuf:"varint,2,req,name=holderCategory" json:"holderCategory,omitempty"`
	// 以下是发布时间筛选，不传返回所有数据，传了返回发布时间属于开始时间到结束时间段内的数据
	BeginTime        *string `protobuf:"bytes,3,opt,name=beginTime" json:"beginTime,omitempty"`
	EndTime          *string `protobuf:"bytes,4,opt,name=endTime" json:"endTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S) Reset()                    { *m = C2S{} }
func (m *C2S) String() string            { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()               {}
func (*C2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S) GetSecurity() *Qot_Common.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *C2S) GetHolderCategory() int32 {
	if m != nil && m.HolderCategory != nil {
		return *m.HolderCategory
	}
	return 0
}

func (m *C2S) GetBeginTime() string {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return ""
}

func (m *C2S) GetEndTime() string {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return ""
}

type S2C struct {
	Security          *Qot_Common.Security             `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	HoldingChangeList []*Qot_Common.ShareHoldingChange `protobuf:"bytes,2,rep,name=holdingChangeList" json:"holdingChangeList,omitempty"`
	XXX_unrecognized  []byte                           `json:"-"`
}

func (m *S2C) Reset()                    { *m = S2C{} }
func (m *S2C) String() string            { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()               {}
func (*S2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C) GetSecurity() *Qot_Common.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *S2C) GetHoldingChangeList() []*Qot_Common.ShareHoldingChange {
	if m != nil {
		return m.HoldingChangeList
	}
	return nil
}

type Request struct {
	C2S              *C2S   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType          *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg           *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode          *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C              *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Qot_GetHoldingChangeList.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_GetHoldingChangeList.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetHoldingChangeList.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetHoldingChangeList.Response")
}

func init() {
	proto.RegisterFile("Qot_GetHoldingChangeList/Qot_GetHoldingChangeList.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0xb3, 0x0d, 0xfe, 0xc0, 0x4b, 0xf2, 0x4f, 0xac, 0xc6, 0x34, 0xa8, 0x64, 0xd9, 0xc1,
	0xec, 0x22, 0x90, 0xc6, 0xc4, 0x84, 0x6b, 0x0f, 0x7a, 0xc0, 0x83, 0x1d, 0x77, 0x83, 0xec, 0xcd,
	0xb6, 0x04, 0x5a, 0x6c, 0xcb, 0x81, 0x0f, 0xe0, 0xd1, 0xb3, 0x5f, 0xd7, 0xac, 0x1b, 0x22, 0x18,
	0x3c, 0x78, 0x6a, 0xdf, 0xe7, 0xf7, 0xbc, 0xcd, 0x93, 0xa7, 0x70, 0xf7, 0xa4, 0xec, 0xf3, 0x3d,
	0xda, 0x07, 0xb5, 0x48, 0x0b, 0x99, 0xf1, 0x7c, 0x26, 0x33, 0x9c, 0x14, 0xc6, 0x0e, 0x8f, 0x81,
	0xc1, 0x4a, 0x2b, 0xab, 0x08, 0x3d, 0xc6, 0x7b, 0xa7, 0x5c, 0x2d, 0x97, 0x4a, 0x0e, 0xab, 0xa3,
	0xb2, 0xf7, 0x2e, 0x4a, 0x7b, 0x0d, 0x76, 0xd7, 0x0a, 0x46, 0x1f, 0x1e, 0x04, 0x9c, 0x25, 0x64,
	0x04, 0x6d, 0x83, 0xf3, 0xb5, 0x2e, 0xec, 0x86, 0x7a, 0xa1, 0x1f, 0x77, 0xd9, 0xd9, 0xe0, 0x9b,
	0x39, 0xa9, 0x99, 0xf8, 0x72, 0x91, 0x6b, 0xf8, 0x9f, 0xab, 0x45, 0x8a, 0x9a, 0xcf, 0x2c, 0x66,
	0x4a, 0x6f, 0xa8, 0x1f, 0xfa, 0x71, 0x53, 0x1c, 0xa8, 0xe4, 0x12, 0x3a, 0x2f, 0x98, 0x15, 0x72,
	0x5a, 0x2c, 0x91, 0x06, 0xa1, 0x17, 0x77, 0xc4, 0x4e, 0x20, 0x14, 0x5a, 0x28, 0x53, 0xc7, 0x1a,
	0x8e, 0x6d, 0xc7, 0xe8, 0xcd, 0x83, 0x20, 0x61, 0xfc, 0x0f, 0xc9, 0x26, 0x70, 0x92, 0x1f, 0x56,
	0x43, 0xfd, 0x30, 0x88, 0xbb, 0xac, 0xbf, 0xb7, 0x9a, 0xcf, 0x34, 0xee, 0x95, 0x28, 0x7e, 0x2e,
	0x46, 0x63, 0x68, 0x09, 0x7c, 0x5d, 0xa3, 0xb1, 0x64, 0x08, 0xc1, 0x9c, 0x99, 0x3a, 0xc5, 0xd5,
	0xe0, 0xe8, 0x37, 0x71, 0x96, 0x88, 0xd2, 0x19, 0xbd, 0x7b, 0xd0, 0x16, 0x68, 0x56, 0x4a, 0x1a,
	0x24, 0x7d, 0x68, 0x69, 0xb4, 0xd3, 0xcd, 0x0a, 0xdd, 0x0b, 0xcd, 0x71, 0xe3, 0xe6, 0x76, 0x34,
	0x12, 0x5b, 0x91, 0x9c, 0xc3, 0x3f, 0x8d, 0xf6, 0xd1, 0x64, 0xd4, 0x77, 0x4d, 0xd4, 0x93, 0xab,
	0x48, 0x6b, 0xae, 0xd2, 0xaa, 0xbe, 0xa6, 0xd8, 0x8e, 0x65, 0x1e, 0xc3, 0xe6, 0xae, 0xb8, 0x5f,
	0xf3, 0x24, 0x8c, 0x8b, 0xd2, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x35, 0xc5, 0xba, 0x52, 0x73,
	0x02, 0x00, 0x00,
}
