// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetStaticInfo/Qot_GetStaticInfo.proto

/*
Package Qot_GetStaticInfo is a generated protocol buffer package.

It is generated from these files:
	Qot_GetStaticInfo/Qot_GetStaticInfo.proto

It has these top-level messages:
	C2S
	S2C
	Request
	Response
*/
package Qot_GetStaticInfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "futugg/pb/Common"
import Qot_Common "futugg/pb/Qot_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Market           *int32                 `protobuf:"varint,1,opt,name=market" json:"market,omitempty"`
	SecType          *int32                 `protobuf:"varint,2,opt,name=secType" json:"secType,omitempty"`
	SecurityList     []*Qot_Common.Security `protobuf:"bytes,3,rep,name=securityList" json:"securityList,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *C2S) Reset()                    { *m = C2S{} }
func (m *C2S) String() string            { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()               {}
func (*C2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S) GetMarket() int32 {
	if m != nil && m.Market != nil {
		return *m.Market
	}
	return 0
}

func (m *C2S) GetSecType() int32 {
	if m != nil && m.SecType != nil {
		return *m.SecType
	}
	return 0
}

func (m *C2S) GetSecurityList() []*Qot_Common.Security {
	if m != nil {
		return m.SecurityList
	}
	return nil
}

type S2C struct {
	StaticInfoList   []*Qot_Common.SecurityStaticInfo `protobuf:"bytes,1,rep,name=staticInfoList" json:"staticInfoList,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *S2C) Reset()                    { *m = S2C{} }
func (m *S2C) String() string            { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()               {}
func (*S2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C) GetStaticInfoList() []*Qot_Common.SecurityStaticInfo {
	if m != nil {
		return m.StaticInfoList
	}
	return nil
}

type Request struct {
	C2S              *C2S   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType          *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg           *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode          *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C              *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Qot_GetStaticInfo.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_GetStaticInfo.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetStaticInfo.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetStaticInfo.Response")
}

func init() { proto.RegisterFile("Qot_GetStaticInfo/Qot_GetStaticInfo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x25, 0xcb, 0xe6, 0x34, 0x13, 0xc1, 0x28, 0x23, 0x4c, 0x18, 0xa5, 0xa7, 0x7a, 0xb0, 0x1b,
	0xd1, 0x83, 0x78, 0x0d, 0x28, 0x82, 0x3b, 0x98, 0x78, 0x97, 0x51, 0x3f, 0xa5, 0x48, 0x9b, 0x2e,
	0xf9, 0x76, 0xd8, 0x1f, 0xf0, 0x77, 0x4b, 0xda, 0xce, 0xa9, 0xd5, 0x53, 0xfb, 0xbe, 0xf7, 0xbe,
	0x97, 0xf7, 0x3d, 0x76, 0xfe, 0x68, 0xf1, 0xf9, 0x0e, 0xd0, 0xe0, 0x12, 0xf3, 0xec, 0xbe, 0x7c,
	0xb5, 0xb3, 0xce, 0x24, 0xad, 0x9c, 0x45, 0xcb, 0x8f, 0x3b, 0xc4, 0xe4, 0x44, 0xd9, 0xa2, 0xb0,
	0xe5, 0xac, 0xf9, 0x34, 0xba, 0xc9, 0x59, 0xd0, 0xb5, 0xc4, 0xee, 0xb7, 0x21, 0xe3, 0x15, 0xa3,
	0x4a, 0x1a, 0x3e, 0x66, 0x7b, 0xc5, 0xd2, 0xbd, 0x03, 0x0a, 0x12, 0x91, 0x64, 0xa0, 0x5b, 0xc4,
	0x05, 0x1b, 0x7a, 0xc8, 0x9e, 0x36, 0x15, 0x88, 0x5e, 0x4d, 0x6c, 0x21, 0xbf, 0x66, 0x87, 0x1e,
	0xb2, 0xb5, 0xcb, 0x71, 0xf3, 0x90, 0x7b, 0x14, 0x34, 0xa2, 0xc9, 0x48, 0x9e, 0xa6, 0xdf, 0x5e,
	0x30, 0x2d, 0xaf, 0x7f, 0x28, 0xe3, 0x05, 0xa3, 0x46, 0x2a, 0x7e, 0xcb, 0x8e, 0xfc, 0x57, 0xf2,
	0xda, 0x82, 0xd4, 0x16, 0xd3, 0xbf, 0x2c, 0x76, 0x37, 0xea, 0x5f, 0x5b, 0xf1, 0x25, 0x1b, 0x6a,
	0x58, 0xad, 0xc1, 0x23, 0x4f, 0x18, 0xcd, 0xa4, 0x17, 0x24, 0xea, 0x25, 0x23, 0x39, 0x4e, 0xbb,
	0xc5, 0x29, 0x69, 0x74, 0x90, 0xc4, 0x1f, 0x84, 0xed, 0x6b, 0xf0, 0x95, 0x2d, 0x3d, 0xf0, 0x29,
	0x1b, 0x3a, 0xc0, 0xfa, 0xc8, 0xb0, 0x3a, 0xb8, 0xe9, 0x5f, 0x5c, 0xcd, 0xe7, 0x7a, 0x3b, 0x0c,
	0xe5, 0x38, 0xc0, 0x85, 0x7f, 0xab, 0x3b, 0x38, 0xd0, 0x2d, 0x0a, 0xe5, 0x80, 0x73, 0xca, 0xbe,
	0x80, 0xa0, 0x4d, 0x39, 0x2d, 0x0c, 0x41, 0xbc, 0xcc, 0x44, 0x3f, 0x22, 0xff, 0x04, 0x31, 0x52,
	0xe9, 0x20, 0xf9, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x02, 0x6f, 0xa7, 0xf0, 0x01, 0x00, 0x00,
}
